### ISSUE TITLE
Promotions feature rework

### ISSUE THREAD

**Issue by JakenVeina** [discord-csharp/MODiX#100]
Need to rework/refactor the promotions feature to match the Repository/Service structure used by all the rest of the DB-related code.

Most notably, DBPromotionRepository needs to NOT create `UserEntity` record directly, as it can cause concurrency issues. `UserRepository` should be the only one messing with the `Users` table.

**Comment by Cisien** [comment]
Promotion to regular should be an automated thing, maybe chat activity + time?

This becomes a nomination/promotion to associate

**Comment by JakenVeina** [comment]
So, mapping out the future of this feature.....

1. Campaigns
1.1 Targets a specific user and role to be (potentially) applied to the user.
1.2 Comments
1.2.1 One per user, per campaign?
1.2.2 Editable?
1.2.3 Text optional?
1.2.4 Sentiment? (approve/disapprove/undecided)
1.3 Can be Accepted or Rejected
1.4 Can be re-opened?
2. Campaign Log Channel?
2.1 Logs all top-level events on a campaign (not comments)
3. Campaign Auto-Create Behaviors
3.1 Fully configurable, per role
3.2 Rules
3.2.1 Evaluated on a schedule (once per day)?
3.2.2 MessageActivityRule
3.2.2.1 Minimum number of messages?
3.2.2.2 Minimum time since first message?
3.2.2.3 Minimum time since last message?
3.2.2.4 Minimum frequency of messages?
3.2.3 InfractionHistoryRule
3.2.3.1 Minimum number of infractions?
3.2.3.2 Ignore infractions older than X?
3.2.3.3 Ignore rescinded infractions?
4. Campaign Auto-Accept Behaviors
4.1 Fully configurable, per role
4.2 Rules
4.2.1 CampaignStatusRule
4.2.1.1 Minimum Age?
4.2.1.2 Minimum "approved" sentiments?
4.2.1.3 Maximum "disapproved" sentiments?
4.2.1.4 Minimum "approved/disapproved" ratio?
4.2.1.5 Minimum Comments?
5. Campaign Auto-Reject Behaviors
5.1 Fully configurable, per role
5.2 Rules
5.2.1 CampaignStatusRule
5.2.1.1 Maximum Age?
5.2.1.2 Maximum "approved" sentiments?
5.2.1.3 Minimum "disapproved" sentiments?
5.2.1.4 Maximum "approved/disapproved" ratio?

I think this structure gets us all the behavior we want out of this feature, and allows for flexibility in configuration, and flexibility in future expansion.

Thoughts?

**Comment by Cisien** [comment]
@mastorm for feedback -- since you have strong feelings about any kind of promotion, auto/otherwise

**Comment by jmazouri** [comment]
Core functionality complete as of #153 , web UI fully updated as of #169
