### ISSUE TITLE
Automated action log

### ISSUE THREAD

**Issue by Cisien** [discord-csharp/MODiX#115]
Things like decaying infractions, invite puring, spam detection, etc should log to a channel. Today that is #mod-log

**Comment by JakenVeina** [comment]
We do have a log for all of these (except spam detection, which isn't yet implemented) in the Form of the `ModerationActions` table. We simply need to add configuration settings to set/store the ID of the channel to push to, and add methods to `IModerationService` to write to the appropriate channel.

**Comment by JakenVeina** [comment]
Claiming this, despite the fact that I can't assign it to myself.

**Comment by JakenVeina** [comment]
This can be closed.
