### ISSUE TITLE
Acknowledge when an infraction has been deleted

### ISSUE THREAD

**Issue by jrusbatch** [discord-csharp/MODiX#128]
Currently issuing `!infraction delete <id>` will delete the reaction without any feedback to the issuer of the command. We should provide some sort of visual feedback, perhaps in the form of a reaction, to indicate that the command was successful.

**Comment by JakenVeina** [comment]
Feedback on all the moderation commands is given through the configured logging channels. Of which, we probably don't have one at the moment.
