### ISSUE TITLE
Discord Infraction Embeds

### ISSUE THREAD

**Issue by ghost** [discord-csharp/MODiX#130]
Listing out the users' infractions in an embed instead of using an ASCII table. It will help with categorizing infractions by type.

**Comment by JakenVeina** [comment]
Repeating what I said in Discord, for posterity...

This should either not be merged until we can link out to a Web UI page to provide full details, or this should include a new `!infraction detail <infractionId>` command to display the fields that don't make it into the embed.

**Comment by Inzanit** [comment]
Yeah this is really low priority
