### ISSUE TITLE
Proposal: Proxy Invite Links

### ISSUE THREAD

**Issue by JakenVeina** [discord-csharp/MODiX#136]
I've heared we use an "aka" url service, which sounds like it may do some of this already, but I'm gonna post this anyway.

This proposal would be to have invites to the server handled EXCLUSIVELY through MODiX.

What MODiX could do is support an HTTP endpoint like "mod.gg/[servername]/join" which simply returns a 302 with an actual invite link. This would have the following benefits:
1. MODiX could either generate a new invite link, per request, or reuse an invite link for only a short period of time, before expiring it.
2. MODiX could enforce rate-limiting on people joining the server. Say, only once every 5 seconds.
3. MODiX could easily implement a "!raidmode" command that prevents people from joining the server, until the raid has ended.

Downsides include:
1. No one would be able to join the server during MODiX downtime.

**Comment by thaumanovic** [comment]
This could potentially be used for analytics (e.g. geolocation of request IP) and human user verification (via a transition page), but I feel like the downsides outweigh these benefits:

- As stated above, if MODiX dies, so does the ability for anyone to join the server. 
- Discord invite links are more "official" and are often implicitly trusted by many users of the platform. Other domains (like mod.gg) may put users off joining/clicking.
- It removes the simplicity of joining the server, and is in large made pointless by the fact that we are joinable via server Discovery and the vanity URL anyway.

I'll suggest closing this issue for the reasons above.

**Comment by Scott-Caldwell** [comment]
I'd agree. It's an interesting idea, but I'm not sure it would really add a ton of value at the moment. Maybe we can revisit this idea later if we can come up with some more use cases.

**Comment by JakenVeina** [comment]
IIRC, the idea spawned from that one big obnoxious raid a few years ago, which we unfortunately had almost no way of dealing with. What features does Discord itself have today, for raid control?

**Comment by Scott-Caldwell** [comment]
https://support.discord.com/hc/en-us/articles/10989121220631-How-to-Protect-Your-Server-from-Raids-101

Not sure what exact criteria Discord uses to determine there's an ongoing raid, but you can set it up to notify when it detects one and force people joining to complete a captcha. We can also pause invites to keep people from using existing invite links. Those are the two main features I'm aware of,
