### ISSUE TITLE
Proposal: Raid Detection

### ISSUE THREAD

**Issue by JakenVeina** [discord-csharp/MODiX#137]
This proposal is to implement some kind of raid detection in MODiX, which can automatically issue an @Staff notification in #mod-log if it detects a potential raid.

The criteria for defining the start of a raid, and end of a raid, are obviously the most interesting part about this proposal. My initial thoughts are...

1. If a certain number of users have joined the server, within a certain timeframe. Say, 10 people in 30 seconds, for example.
2. Potentially, a lower threshold, for users that were created briefly before joining.
3. Once a notification has been issued, there would need to be a cooldown to prevent repeats during the raid. Say, "once an hour has passed with no new users joining".

**Comment by Inzanit** [comment]
Should post straight to #moderation and ping all Staff.

The raid mode should be initiated manually only and will lock down all channels to >= regular with an automatic message posted to general.

Raid mode automatically get's turned off an hour in, or earlier with staff intervention.

**Comment by Insire** [comment]
There is also the possiblity to switch new comers to an "overflow channel", which is usually notavailable.

Instead of just locking all the channels, we could redirect any newcomers to that channel. Lock that down for comments and let only users with roles write in there. Idk if thats feasable.

Preferably all the other channels with existing users and discussions are unaffected.

**Comment by JakenVeina** [comment]
There's a lot of different ways we could handle tgebactual raidmode command, and yeah, it should definitely be staff-initiated.

All I'm worried about in this issue is the potential to auto-notify staff that intervention might be needed.

See #135, #136

**Comment by thaumanovic** [comment]
This issue is made obsolete by Discord's own implementation of raid detection.

**Suggested action:** Close issue.

**Comment by Scott-Caldwell** [comment]
Agreed, aside from Discord's built-in raid detection, [Accord](https://github.com/patrickklaeren/Accord) has also been meeting our needs in this respect pretty well so far.

Closing for now, but we can revisit if the existing solutions aren't cutting it later.
