### ISSUE TITLE
Bot should respond with "User not found" when searching for infractions for a user that it doesn't know about

### ISSUE THREAD

**Issue by jrusbatch** [discord-csharp/MODiX#138]
MODiX reacts to infraction searches for unknown users in the same way it reacts to invalid commands. This is less than ideal since it leads users to believe that the bot is broken when really there were just no search results:

![image](https://user-images.githubusercontent.com/423549/43805793-2b57d7d4-9a6f-11e8-8eda-377d0a6a5661.png)

We should either stop treating "User not found" as an error or we should provide a more user-friendly message when it occurs so that it doesn't look like the bot is broken.

**Comment by jmazouri** [comment]
Fixed as of #180
