### ISSUE TITLE
[Proposal] Tag System

### ISSUE THREAD

**Issue by NinjaKitt3n** [discord-csharp/MODiX#147]
I'd like to propose a `Tag System` implementation as per R.Danny

This would allow Tag Creation/Removal/etc to be restricted easier (by MODiX Auth Claims)

**Comment by JakenVeina** [comment]
What's a tag?

**Comment by NinjaKitt3n** [comment]
![image](https://user-images.githubusercontent.com/32270733/44529262-8ee59e00-a6e3-11e8-8759-bacadb4dc575.png)

**Comment by JakenVeina** [comment]
Gooootcha. So, basically, pre-defined static messages. Sounds great to me.
