### ISSUE TITLE
[Proposal] Extend !info to show Infraction Counts

### ISSUE THREAD

**Issue by NinjaKitt3n** [discord-csharp/MODiX#154]
Current Info output:
![image](https://user-images.githubusercontent.com/32270733/44849602-8d235980-ac52-11e8-9c57-4c8d48ec2dc2.png)

I'd like to propose an increase in information to show infraction count(s)
```
> Infractions
Given: 999
Received: 0
```

**Comment by jmazouri** [comment]
Actually a work in progress - I just need to figure out what PR I can fit it into. Great minds think alike!

**Comment by sylveon** [comment]
Infraction count should not be displayed in public channels.

**Comment by jmazouri** [comment]
@sylveon Do you foresee that causing issues? Rowboat always showed infraction counts. Perhaps we can base it on who is running the command?

**Comment by sylveon** [comment]
Infractions and notes are sometimes done in private channel for a reason. A user being able to see its own infraction count is fine, but someone under associate shouldn't be able to query the infraction count of others.

**Comment by jmazouri** [comment]
Resolved as of #180
