### ISSUE TITLE
Proposal: Ability to change infraction severity

### ISSUE THREAD

**Issue by ghost** [discord-csharp/MODiX#155]
Pretty self explanatory. Add the ability to change the severity of any infraction. We have the ability to change the comment on an infraction. Being able to change the rank of an infraction would compliment this. This also works well with #74 and #66 too.

![image](https://user-images.githubusercontent.com/4664407/44884462-777d5680-ac89-11e8-83ac-6d2ae724f8ef.png)

**Comment by QuesosNachos** [comment]
I don't know what he meant
