### ISSUE TITLE
Proposal: Starboard Functionality

### ISSUE THREAD

**Issue by ghost** [discord-csharp/MODiX#161]
Have Modix manage the Starboard channel. Modix will perform the same tasks that R. Danny performs for the Starboard channel. 

![image](https://user-images.githubusercontent.com/4664407/45600814-e6b8b180-b9d0-11e8-85eb-48558896f5d8.png)

**Comment by JakenVeina** [comment]
Do it.

**Comment by QuesosNachos** [comment]
I'll claim this. How do you assign people to issues?

**Comment by JakenVeina** [comment]
Only a few people in the org have permissions to do that.

**Comment by calledude** [comment]
Seems as if he deleted his account. If this is still open I can give it a try.

**Comment by jmazouri** [comment]
@calledude Go for it! Consider yourself officially / unofficially assigned.

**Comment by jmazouri** [comment]
Implemented as of #315

**Comment by calledude** [comment]
Oof, I completely forgot to tag this issue. My bad!
