### ISSUE TITLE
Restore and retrofit CodePasteHandler

### ISSUE THREAD

**Issue by JakenVeina** [discord-csharp/MODiX#165]
Fix issues related to temporary workaround #164.

**Comment by thaumanovic** [comment]
Related code seems to have been removed at some point.

**Comment by Scott-Caldwell** [comment]
For context, the tldr thing was a feature years ago where we had a :tldr: emoji and, if 3 (iirc) people reacted with that emoji on a message, it would remove the original message, paste the contents of the message into https://paste.mod.gg, and respond with a link to the paste. The intent was to help clean up chat when someone posted a massive wall of code.

There were issues where the feature was abused, and it's just generally not a great feature. It's jarring and confusing for the person whose message is deleted and re-posted, and it's always just going to be easy to abuse no matter what we do.

I don't think there's any interest in re-adding the feature, so I think this can just be closed.
