### ISSUE TITLE
Proposal: Implement !cleanup <#OfMessages> command

### ISSUE THREAD

**Issue by ghost** [discord-csharp/MODiX#168]
This command could be used for cleaning/deleting a large number of messages in a channel.

Usage: !cleanup 5
Result: Deletes the last 5 messages in the channel the command is executed in.

Usage: !cleanup 5 channelID/channelName
Result: Same thing, but with the option to pick channels

**Comment by QuesosNachos** [comment]
I'll claim this

**Comment by JakenVeina** [comment]
Certainly similar.
