### ISSUE TITLE
[Feature] Additional Language Support

### ISSUE THREAD

**Issue by Foxtrek64** [discord-csharp/MODiX#181]
This is definitely one for the back log, but I feel like we should be able to leverage other Roslyn-compatible languages.

I will be submitting a PR for this as I develop code. However, I will be primarily focusing development on the back-end ([CSDiscord](https://github.com/discord-csharp/CSDiscord)) first, then I will swing around and add capability to the bot. To see what languages I'm looking to support, go see [issue 18](https://github.com/discord-csharp/CSDiscord/issues/18) on the CSDiscord repository.

Bot-side changes:
[ ] Manual Language Detection (based off the provided lang in the formatted code block provided by the user)
[ ] Automatic Language Detection (Not entirely sure how to do this one in a way that's efficient)
[ ] Send formatted JSON to web service (CSDiscord) with fields for the detected language and the code to compile.

Edit: From the user's POV, nothing should change. During development, at least until the automatic language detection comes into play, there may be a requirement for users to use a formatted code block (three back ticks and then the lang tag).

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
