### ISSUE TITLE
Support for Benchmark.Net in the REPL

### ISSUE THREAD

**Issue by mastorm** [discord-csharp/MODiX#183]
It would be pretty neat to be able to benchmark. I mean, the results are flaky as fuck and non-dependable, but it still would be nice. 

https://benchmarkdotnet.org/

**Comment by spixy** [comment]
If benchmark would run a minute or two, wouldn´t that cause connection timeout?

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
