### ISSUE TITLE
Decoupling the Modix Asp.Net Core Service from the bot

### ISSUE THREAD

**Issue by mastorm** [discord-csharp/MODiX#194]
Theres multiple advantages to this, one of them being a much more decoupled architecture.

This imposes problems, one of them being communication between the modix host and the modix webserver. Maybe we could go for a Messaging Queue?

**Comment by jmazouri** [comment]
Currently, large portions of the webserver rely on the fact that a DiscordSocketClient is always available. To go forward with this, we will need to highly refactor that to depend on a more traditional authentication architecture, and/or potentially create a third intermediary service that exclusively handles communication with the Discord API that both the Webserver and Bot can utilize.

There are some refactoring efforts by @jrusbatch here: https://github.com/discord-csharp/MODiX/pull/193/ that attempt to rearchitect our internals, though it is still structured monolithically - after his changes are merged, I will investigate the potential of shifting the architecture further to a hosted service model. 

Verrrry simplified tl;dr:
Current architecture: Modix(Bot(WebApi))
New architecture: Modix(WebApi(Bot))
Potential Future Architecture: Modix(WebApi, DiscordService, Bot)

Also, @NullEntity looked into potentially implementing MediatR for handing Discord.Net events in a more loosely coupled / easier to structure way, which will likely be implemented as part of the "Future" architecture - this will make it easier to break the bot apart in the future.

**Comment by mastorm** [comment]
I will put my extended weekend into developing a prototype for the potential Architecture, because this is essentially what my plan was with the whole decoupling-architecture thing. 

Heres my plan:
- [ ] Integrate a MessageQueue into the system(RabbitMQ/IronMQ?)
- [ ] Start refactoring every call from the Webserver to utilize the MQ
- [ ] Once i have all the calls ported over, I can start decoupling the Webservice from Modix
- [ ] Rinse and repeat for Bot logic vs Discord service interaction later

The seperation of the webservice would keep me busy for a couple of days probably and will also require some work on the hosting part since we need a MQ set up, but I think @Cisien can provide that in a sec considering his huge amount of containerization experience.

**Comment by mastorm** [comment]
Extending on the Idea of using RabbitMQ, I think Apache Kafka could do nice in out scenario.

**Comment by JakenVeina** [comment]
What advantage does a Messaging queue give us? We already have a mechanism for decoupling in the form of Modix.Services. Nothing in the Web Frontend has any direct dependency to Discord.NET, it all goes through service layer methods/interfaces, the same ones that the Discord Frontend uses. E.G. `IModerationService`, `IPromotionsService`, etc.

There's definitely room for improvement and refactoring the service layer, as we've discussed here and there. For example, we discussed splitting several of these services into public-facing and internally-facing interfaces (I.E. an interface for the two frontends to use, and an interface for other services to use). 

A distinct Message Queue just seems odd to me. In fact, that's kinda what we already have. Requests coming from the Web API and events fired by Discord.NET are both handled the same way. In both cases, the relevant frontend builds up a new `IServiceScope` for the processing of that request/event, and invokes the appropriate `Modix.Service` call to initiate it. From there, the `ThreadPool` essentially acts like an async message queue by scheduling all the `Task` based work that spawns off of the initial service call.

**Comment by mastorm** [comment]
After spending a lot of time researching this issue, I think its too much work for too little profit. Process decoupling was what I am aiming for, but considering that the Web Frontend has hard wired dependencies to the Discord Frontend(See ModixController in the Webproject), the coupling is just too tight and major refactorings would be needed. Since we dont run into any issues using the current structure, I will just close the Issue up.
