### ISSUE TITLE
Web frontend for user info (I.E. !info command)

### ISSUE THREAD

**Issue by JakenVeina** [discord-csharp/MODiX#195]
Realized today that there's no web UI equivalent for the !info command.

**Comment by JakenVeina** [comment]
Also, this seems like a good candidate for a `newbies only` tag, or whatever.

**Comment by Crowes** [comment]
In what kind of state is the UI in at the moment? I couldn't figure out what is built with but I'd be looking to contribute to Modix here, but I'd like to know whether it's due a nice makeover for better supporting stuff like this or whether we like it as it is but want features like this implementing.
