### ISSUE TITLE
Feature request: mansplain

### ISSUE THREAD

**Issue by JohanLarsson** [discord-csharp/MODiX#211]
Not sure if this is possible but the use cases are:

1. I write an ~answer that is wrong or bad. Then other members of chat can add :manplain: emojis on the message. If a chat message gets enough mansplain votes maybe it could be rendered differently.
2. I guess at something and tag my own post with mansplain to trigger mansplain rendering.

**Comment by JakenVeina** [comment]
How would a message be rendered differently? Like, MODiX reposts it as an embed?

**Comment by JohanLarsson** [comment]
Not sure what the possibilities are here. If modix reposts it author gets lost right? 
Maybe it is possible to add a bigger image as reaction emoji somehow?

**Comment by JakenVeina** [comment]
Yeah, if MODiX reposts, then MODiX is the author. The repost could list what the original author was, but the new message itself is fixed to MODiX. Plus, the new message will always show up at the bottom of the channel, not adjacent to the original.

**Comment by jmazouri** [comment]
This needs some additional concept work I feel. Closing for now due to inaction.
