### ISSUE TITLE
Feature Request: Granular Mentionable Roles

### ISSUE THREAD

**Issue by jmazouri** [discord-csharp/MODiX#213]
This is an addition that would support things like @Staff mentions. Currently, in order to mention a role it must be set as globally mentionable on the server - this has caused a number of incidents where people have used it mistakenly to ask questions, etc. 

This feature would, by default, make all "mentionable" roles un-mentionable within Discord - then, users or roles with the correct designation (Associate and up?) could use a command like "!mention staff" or just "!staff", which would toggle the role mention on, have the bot send a message, then toggle the role mention off again (the same technique is used for the TCD announce bot here: https://github.com/TheCodingDen/tcdannounce).

This lets us have more granular control over who can actually mention these roles, while still making it easy for those who can.

**Comment by JakenVeina** [comment]
Seems doable. Database maps the roleId of the minimum rank needed to mention, to the roleId of the mentionable role. Plus a web page for configuring?
