### ISSUE TITLE
Feature request: Ability to edit promotion comments

### ISSUE THREAD

**Issue by sylveon** [discord-csharp/MODiX#224]
If our opinion changes, or we want to add details or fix typos, this would be great to use.

**Comment by JakenVeina** [comment]
Am I being too paranoid if I say we should implement this the way we do for infractions etc. where we don't update the existing comment, but we instead mark it as deleted/modified, and create a whole new one, so that we could always look at the history?

**Comment by Scott-Caldwell** [comment]
Similarly, how do we want this to work with the promotion log channel? I suppose we could either edit the existing message, or delete it and add a new message.

I'm thinking just delete the old one and a new message. Might seem a little overkill for just fixing typos, unless we added a "Minor Edit" flag or something, but that might get a little complicated
