### ISSUE TITLE
Time limit between promotion campaigns

### ISSUE THREAD

**Issue by Scott-Caldwell** [discord-csharp/MODiX#225]
With regard to recent comments in #promotion-log, should MODiX enforce a time limit between campaigns for the same user for the same rank?

I haven't seen it abused much so far, and users with the ability to start a campaign should be trusted enough not to abuse the feature anyway. Still, starting campaigns too close together can cause some controversy, and it's probably worth discussing. I can see how it could easily get out of hand.

**Comment by JohanLarsson** [comment]
I think the current campaign shows why not having a limit is good!

**Comment by jmazouri** [comment]
This hasn't been much of an issue, so I'll close this for now.
