### ISSUE TITLE
Include additional logging of guild events

### ISSUE THREAD

**Issue by jmazouri** [discord-csharp/MODiX#226]
Currently, in our server, we use DynoBot to log member joins, leaves, voice channel joins/leaves, nickname changes, and (rather redundantly) message deletions. We should introduce logging for some of these events in the same vein as message logging, and eventually, we should remove Dyno from the server altogether. I will investigate an implementation.

**Click below for examples from dynobot:**
<details>

![image](https://user-images.githubusercontent.com/1239222/48870611-80288900-edaf-11e8-8d93-27af08af5443.png)
![image](https://user-images.githubusercontent.com/1239222/48870620-8880c400-edaf-11e8-993f-72f37a6e088f.png)
![image](https://user-images.githubusercontent.com/1239222/48870636-92a2c280-edaf-11e8-8a73-0988a0738a6f.png)

</details>

**Comment by Erlite** [comment]
I'm willing to start helping out with Modix, I could help if needed.

**Comment by jmazouri** [comment]
Sure! This feature will probably look very similar to [MessageLogBehavior](https://github.com/discord-csharp/MODiX/blob/master/Modix.Services/Core/MessageLogBehavior.cs)  - create a class that extends from BehaviorBase and implement the events you need. You'll then want to log those events in the same way MessageLogBehavior does - call `IDesignatedChannelService#SendToDesignatedChannelsAsync` with the message/embed and the appropriate [`DesignatedChannelType`](https://github.com/discord-csharp/MODiX/blob/master/Modix.Data/Models/Core/DesignatedChannelType.cs).

Here are my recommendations for new designations, one for each log type:
- MemberJoinLog (joins and leaves from the server)
- MemberVoiceLog (joins and leaves from voice channels)
- MemberModificationLog (nickname changes) 

Not too attached to any of the names specifically, though.

**Comment by Erlite** [comment]
Alright, thanks for the tips! I might name `MemberModificationLog` something like `MemberUpdateLog`, but I'll check out `MessageLogBehavior`.

**Comment by Erlite** [comment]
Been a while since I commented here, but I forked and I'll start work on this.

**Comment by Scott-Caldwell** [comment]
Actions that Dyno is able to log and whether MODiX is also able to log that action:
- [ ] Member Joined
- [ ] Member Left
- [ ] Member Banned
- [ ] Member Unbanned
- [x] Message Edited
- [x] Message Deleted
- [x] Bulk Message Deletion
- [ ] Channel Created
- [ ] Channel Deleted
- [ ] Role Created
- [ ] Role Deleted
- [ ] Role Updated
- [ ] Role Given
- [ ] Role Removed
- [ ] Nickname Changed
- [ ] Member Joined Voice Channel
- [ ] Member Left Voice Channel
- [ ] Member Moved to Voice Channel

Thoughts:
- It would be nice to have the option to toggle each of these individually in case we decide we want more or less logging.
- It's probably fine just to have a single channel for non-message logging and one for message logging like we do currently.

**Comment by jmazouri** [comment]
Out of those, the ones we probably care about are:

- Member Joined
- Member Left
- [ ] Role Given
- [ ] Role Removed
- [ ] Nickname Changed

**Comment by JakenVeina** [comment]
Another question: how much of that could be retrieved from the audit logs?

**Comment by jmazouri** [comment]
The list of audit log events is here:

https://discordapp.com/developers/docs/resources/audit-log#audit-log-entry-object-audit-log-events

The only thing from that list it can provide context for is Role Given / Role Removed, in the form of `MEMBER_ROLE_UPDATE`.

**Comment by JakenVeina** [comment]
So, in the interest of having Discord be the source of truth, I think we need to pull info from there, primarily. We can dupe/denormalize it locally for the sake of performance, if need be.

**Comment by calledude** [comment]
My guess is that d.NET already pulls that information from there into these events it provides.

**Comment by JakenVeina** [comment]
No, Discord.NET events all come through the socket/gateway connection. I don't think they have anything that supplements from the audit logs, especially considering they were only recently added.

**Comment by calledude** [comment]
> So, in the interest of having Discord be the source of truth,

> My guess is that d.NET already pulls that information from there into these events it provides.


Wouldn't that make those events good enough?

**Comment by jmazouri** [comment]
> Wouldn't that make those events good enough?

The gateway events don't contain information like who changed the nickname or who modified the roles, just that it happened.

**Comment by calledude** [comment]
> The gateway events don't contain information like who changed the nickname or who modified the roles, just that it happened.

Ooh, I didn't know that that type of information was even a thing. I rest my case.

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
