### ISSUE TITLE
Add a force version of `!promotions accept` to bypass campaign time limit

### ISSUE THREAD

**Issue by Scott-Caldwell** [discord-csharp/MODiX#234]
There is currently no way to accept a campaign before the current 48-hour time limit. We should consider adding a `force` version of the existing `!promotions accept` command.

Design:
1. Should include a button in the web interface.
2. Consider whether a new parameter (e.g. `!promotions accept force <id>`) or a new command (e.g. `!promotions forceaccept <id>`) makes more sense/is cleaner. Also consider whether to skip the command altogether and only make the functionality available from the web interface.
3. Consider whether adding a new claim specific to this version of the accept command might make sense.
4. Should perform all of the validations that the `!promotions accept` command performs except for the time limit validation.

**Comment by JakenVeina** [comment]
...why? The entire point of the promotions system is to allow voting. If the desire is to simply bypass that, as was the case for will today..... we already have that. Just assign the roles directly in Discord.

**Comment by jmazouri** [comment]
I tend to agree with @JakenVeina - although, ensuring all rank changes go through the promotions system would allow us better tracking / visibility. To that end, these are my recommendations: 

1. Definitely, though it would require a bit of additional API work
2. I think we should go with an interactive command, similar to the recently added `!nominate` shortcut. A warning should come up when doing `!promotions accept` for a campaign that is still within the time limit, with confirm/cancel reactions.
3. Perhaps bypass it for `Administrator`(s) (tied to #227)

The 48 hour delay is mostly procedural - it was implemented to ensure we don't be too hasty in promoting someone who may not deserve it - so bypassing it shouldn't be an ordeal.

**Comment by JakenVeina** [comment]
Yeah, I'll agree that the 48 hour delay, in general, shouldn't be hard-coded. Having be a confirmation-based action sounds nice.

**Comment by jmazouri** [comment]
Done as of #263
