### ISSUE TITLE
Implement base for infractions

### ISSUE THREAD

**Issue by mastorm** [discord-csharp/MODiX#26]
This should act as a baseline to add different kinds of moderational actions upon.

An infraction could be the baseclass for tempmutes, warnings, bans etc. It should contain stuff that can be searched through for an user, meaning there should be an unique identifier, it should be associated to a user(the bad guy) and a moderator(the good guy). A reason should be required.

The interface for searching throw them should be idiomatic and easy. Maybe we can do that using memorable shortcuts? This needs to be iterated upon

**Comment by JakenVeina** [comment]
See #75.
