### ISSUE TITLE
Proposal: Frontend Proposals

### ISSUE THREAD

**Issue by BlackCentipede** [discord-csharp/MODiX#261]
**Proposals:**
1. Removing Infraction Table for JSGrid: http://js-grid.com/ for maintainable code 
2. Cache image for discord widget in case it fail to connect to the server and have onerror event subscribed to override src to locally cached image. 
3. Add legal summary stubs (Terms of Use and Privacy Policy) at the front page (Making use of white space) 
4. Implement Vuetify? https://vuetifyjs.com/en/getting-started/quick-start

**Fixes:**
1. Remove Icon white border around portrait image that Dk pointed out

**Comment by jmazouri** [comment]
Layout/component concerns: We use https://github.com/xaksis/vue-good-table/ and https://github.com/jgthms/bulma currently, which are well maintained (and though I have issues with the table component, we'd likely switch to our own solution before adding a different library).

Legal summaries are a good suggestion, though as we're not really a legal entity I'm not sure on how to write them, or how applicable they would be.

Hope that answers your questions - this is quite old of an issue so I'll close it now. For further questions/concerns, feel free to make a new one.
