### ISSUE TITLE
DiscordSocketClient.ReactionAdded bug?

### ISSUE THREAD

**Issue by JakenVeina** [discord-csharp/MODiX#264]
Captured 2 `NullReferenceException`s today in #modix-log

https://paste.mod.gg/hexenisana.json
https://paste.mod.gg/cakufetewi.json

Both are coming from `CommandErrorHandler`, being executed in response to a `ReactionAdded` notification, on literally the first line of logic within the method.

I'd guess this is another bug related to Discord.NET's caching, and the `Cachable<IUserMessage>` actually has a `null` value.

**Comment by jmazouri** [comment]
A mitigation has been implemented with https://github.com/discord-csharp/MODiX/commit/3d2367911458c80ce20f8e783df361ab624c2fe2 , however I'm not sure on the true origin. Closing for now.
