### ISSUE TITLE
Promotions approval percentage

### ISSUE THREAD

**Issue by Scott-Caldwell** [discord-csharp/MODiX#274]
Should the calculated approval percentage for campaigns be `Approved / (Approved + Abstained + Opposed)` or `Approved / (Approved + Opposed)`? I noticed that the `!promotions` command includes abstains in the total, but the progress bar on the web page doesn't. Which is the preferred method?

**Comment by jmazouri** [comment]
It should be a percentage of the approving votes vs the total of approved or opposed - abstaining votes should not be counted at all. The `!promotions` command should definitely be updated if we're counting it inaccurately there.

**Comment by JakenVeina** [comment]
I never understood the purpose of `Abstain` anyway. I assumed they should be included in totals, because if they're not, then from a practical point-of-view they HAVE no functional purpose, and we might as well get rid of them altogether.

**Comment by Sutarodo** [comment]
Looking at picking this up. Current code seems to summarise as `round((approved / total) * 100)`, are we agreed on `rround((approved / ((approved + opposed) - abstained)) * 100)`?

**Comment by jmazouri** [comment]
Yes, the math should be `Approved / (Approved + Opposed)` - abstained are not taken into account at all. The frontend is using the correct logic - see the bars on https://mod.gg/promotions for an example. For example, a campaign with 4 upvotes, 5 neutral votes, and 1 downvote should be at 80%.
