### ISSUE TITLE
Proposal: Tracked code reviews

### ISSUE THREAD

**Issue by monoclex** [discord-csharp/MODiX#275]
This propsal is to implement a way to keep track of code reviews. Code reviews that haven't been reviewed would be kept in a list to be viewed, and then once reviewed, could be removed from that list.

Some additional ideas for it:

- Sometime, it would be feasible to branch this out and call it "Tracked requests", and extend it to #beginner-questions, #game, #web, #database, etc. and other channels, so that nothing would be left without a response.

- The location of the list could possibly utilize the discord pinned messages, or the front-end.

- Maybe there could even be some kind of scoreboard for keeping track of users who response frequently, though this is up for consideration, and overall, might not be a good idea.

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
