### ISSUE TITLE
Proposal: remove !tag command trigger message

### ISSUE THREAD

**Issue by spixy** [discord-csharp/MODiX#279]
After successful execution of `!tag` command,
remove message that triggered this command (for example `!tag yellowbook` message)

**Comment by HurricanKai** [comment]
I don't like that idea, because then it just results in an out of context link, and that one messages is no big deal anyways.
Also not nice vor moderation, because it isn't visible who executed the command.

**Comment by Scott-Caldwell** [comment]
Hmm. Why would this be useful? Is it just to reduce clutter? My thought was that it's at least helpful to know who invoked the tag and what the tag name was.

It might be possible to add an embed as a header or footer or something in the tag response that contains that information. If that were the case, I think I'd be more ok with removing the invocation message.

**Comment by spixy** [comment]
yes to reduce clutter, header info with name of user is good idea

**Comment by Inzanit** [comment]
Could always be toggled on a per-tag basis 🤷‍♀️

**Comment by Inzanit** [comment]
RE Moderation, we're able to see deleted messages, so that's not a concern @HurricanKai

**Comment by jmazouri** [comment]
Inline tag usage (ex. `$yellowbook`) helps resolve clutter in a similar way. Considered resolved as of #351
