### ISSUE TITLE
Refactoring: Extract common behavior of some duplicated frontend components

### ISSUE THREAD

**Issue by jmazouri** [discord-csharp/MODiX#283]
Currently, things like our table implementation on the Infractions and Tags pages have a lot of copy+pasted functionality that could be extracted to a generic base component - which would be useful for later table-based views, like mod logs. The Role and Channel designations have quite a bit of copied stuff.

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
