### ISSUE TITLE
Begin utilizing server audit logs for additional data

### ISSUE THREAD

**Issue by jmazouri** [discord-csharp/MODiX#287]
Leave some ideas in the comments - one example is pulling who deleted a message (if it wasn't the user who sent it, it should be in the audit log, and thus can be included in our logs).

**Comment by jmazouri** [comment]
Bans are now synced as of #337 (and some subsequent fixes...)

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
