### ISSUE TITLE
Quotes can be used to leak a message from a private channel

### ISSUE THREAD

**Issue by sylveon** [discord-csharp/MODiX#296]
![image](https://user-images.githubusercontent.com/6440374/53035131-bd4df700-3442-11e9-85ab-b6f9bb102822.png)

**Comment by jmazouri** [comment]
We've discussed this before and came to the conclusion that if we trust a user to see a channel, we can trust them to not leak from that channel - it's not much different from taking a screenshot of a message, etc.

**Comment by Cisien** [comment]
in addition, the sensitive channels wouldn't have the bot in them

**Comment by sylveon** [comment]
Closed as being a feature then
