### ISSUE TITLE
Modix logons are expiring more often than intended

### ISSUE THREAD

**Issue by jmazouri** [discord-csharp/MODiX#307]
In code the cookie expiration time is set to 7 days, but in reality it's closer to 24 hours. Check whether the `dataprotection` folder is being persisted as a volume properly and/or whether cookie settings are actually applying.

**Comment by Inzanit** [comment]
Wondering if this has anything to do with #661

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
