### ISSUE TITLE
Display same name on promotions page and discord channel

### ISSUE THREAD

**Issue by shadowkras** [discord-csharp/MODiX#310]
When a user is picked for promotion, their name on the promotions page may be different from their actual discord id, which is shown on the promotions log discord channel. So, we could be looking for an user that has a different name and may not recognize her at first.
Their identification would work better if either it could normalize as their discord id, or display both their user name and discord id on the promotion page.

**Comment by jmazouri** [comment]
This has been improved by allowing all users to see the "More..." button (after #327 it'll be called "Info") on promotions pages now, which includes the user ID and a copy/pastable `!info` command.

**Comment by Scott-Caldwell** [comment]
Fixed in #402.
