### ISSUE TITLE
Logging - Probably primarily in the webinterface since its searchable there? Access should be controlled through permission system

### ISSUE THREAD

**Issue by mastorm** [discord-csharp/MODiX#33]

**Comment by JakenVeina** [comment]
As far as moderation actions go, I'm planning to keep a table with a history of all actions, which we can build a web UI for, as well as optional dumping to a #mod-log channel.

**Comment by jmazouri** [comment]
Logs implemented in frontend:

- [x] Message Deletions
- [x] Infractions
- [x] Promotions (implicitly)

Exceptions are logged via webhook to `#modix-log` now, though not centralized.
