### ISSUE TITLE
Change MODiX/Modix.Services/Moderation/AttachmentBlacklistBehavior.cs to a Whitelist

### ISSUE THREAD

**Issue by NinjaKitt3n** [discord-csharp/MODiX#348]
Zero-Trust Principle -> Apply Exceptions
is inherently more secure than
Allow Everything -> Except

Therefore we should swap the blacklist behaviour to a whitelist behaviour.

CREDIT to : Rist for pointing it out.

**Comment by Scott-Caldwell** [comment]
The obvious next question would be... what extensions should we whitelist?

**Comment by NinjaKitt3n** [comment]
> The obvious next question would be... what extensions should we whitelist?

I assume this would be a discussion better had in Discord and the output summary applied here? :)

**Comment by NinjaKitt3n** [comment]
Anyone have any thoughts on this ?

**Comment by Cisien** [comment]
considering this really isn't a security feature, i think a whitelist + moderators is adequate. It's mostly intended to keep the most common dangerous files from being blindly downloaded and run on accident

**Comment by NinjaKitt3n** [comment]
> considering this really isn't a security feature, i think a whitelist + moderators is adequate. It's mostly intended to keep the most common dangerous files from being blindly downloaded and run on accident

Fair, feel free to close if desired.

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
