### ISSUE TITLE
Frontend Redesign / Design Consistency

### ISSUE THREAD

**Issue by jmazouri** [discord-csharp/MODiX#414]
It's been expressed by some that our frontend is a bit... plain. While I prefer the term "utilitarian", it's fair to say there's some minor inconsistencies in our design language, as well as aspects of the UI that could be improved or otherwise redone.

Currently we use [Bulma](https://github.com/jgthms/bulma) as the frontend framework of choice, which I believe provides a solid framework - but I am not opposed to trimming a lot of it out in favor of our own components.

Our frontend framework, Vue, also has somewhat of a part in this - we can separate some commonly used components into Vue components so they can be reused. We should also investigate refactoring the codebase to make this less annoying to do (like globally importing some components, or extending/enhancing the base `ModixComponent` more often). As with all things, however, we need to be careful not to make them *too* piecemeal. 

CC @Sutarodo @JasonHughes94 @Scott-Caldwell

**Comment by Sutarodo** [comment]
I intend to work on a redesign in Materialize tomorrow. Got some ideas for a nice modern web interface. Then I'll investigate how we can utilise the components we have.. hopefully it doesn't turn into a rewrite.

**Comment by JasonHughes94** [comment]
I may have some time at one point this weekend to help out with this. I can mostly help out with the design and implementation of the CSS. Soon as it comes to Vue tho I'm a potato :D

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
