### ISSUE TITLE
Starboard sometimes makes duplicate posts

### ISSUE THREAD

**Issue by jmazouri** [discord-csharp/MODiX#438]
This was discovered recently after a post was starred many times in short succession:

![image](https://user-images.githubusercontent.com/1239222/56098182-dbc4f180-5ecb-11e9-9912-fa420810bb51.png)

This is likely a race condition in the check for [`messageEntity?.StarboardEntryId != null`](https://github.com/discord-csharp/MODiX/blob/master/Modix.Services/Starboard/StarboardService.cs#L105) in StarboardService - we may need to implement a transaction for it via [`BeginTransactionAsync`](https://github.com/discord-csharp/MODiX/blob/master/Modix.Data/Repositories/RepositoryTransactionFactory.cs#L56) as per our other services.

**Comment by calledude** [comment]
Might be a good time to refactor the entire message-repo.

**Comment by calledude** [comment]
I can do it if nobody wants to or has started with it yet

**Comment by calledude** [comment]
Fixed in #463 ... Hopefully :)
