### ISSUE TITLE
Discuss: Logging Strategy

### ISSUE THREAD

**Issue by JakenVeina** [discord-csharp/MODiX#442]
So, since I'm in the process of refactoring and writing tests for a lot of existing stuff, I realized I could easily be adding more logging logic, while I'm at it. I then realized I don't know much about how Serilog really works, or what the differences and advantages are of the 3 or so different styles of logging we've got littered throughout the application.

I did a little experimenting with Serilog and Microsoft's logging, to see what our options are.

![image](https://user-images.githubusercontent.com/26645431/56106321-27948c80-5f06-11e9-9c47-f4f9e45d9d9e.png)

https://paste.mod.gg/ketimamuci.cs

The lines with the timestamps are the ones generated by the Serilog Console sink. The other one is the Microsoft Console sink.

It required a little custom finagling to get the class name to output through the Serilog sink.

Personally, I think I like the idea of using injected `ILogger<T>` types. I didn't at first, since having it inject kinda implies that it's functionality we should be testing (which we definitely shouldn't). But, to get the class name attached (which I think we definitely definitely want) requires either using `ILogger<T>` or `Log.ForContext<T>()` so if we gotta create and maintain an instance, we might as well inject it. Plus, with an injected logger, we could setup a sink that dumps logs into the test output window.

**Comment by Sutarodo** [comment]
We should probably consolidate it into one logging project perhaps (so we can swap out the logging package we use at any point and the references wont break in the whole solution), and stick with one logging package for now. NLog is the one we use at work because of it's features compared to others like Serilog, but then again Microsoft's own Logging is built in to core I'm guessing?

**Comment by Scott-Caldwell** [comment]
My impression was that the primary selling point of Serilog's static logger was the convenience factor, but since that doesn't even get us what we want out of logging, I'm quickly losing interest in it.

If Serilog has any advanced features or special flexibility, it doesn't seem like we're taking advantage of any of that anyway, so I'm inclined to say that the basic logging from the Microsoft logger is plenty.

**Comment by jmazouri** [comment]
`Microsoft.Extensions.Logging` is itself a logging abstraction - other loggers and sinks can be plugged into it, and we can use `ILogger<T>` from our code in a library-agnostic fashion. It also supports structured logging, so if we get a proper log sink set up at some point, we'll have better searchability. 

We are ultimately only using Serilog - this call in `Program.cs` hooks into M.E.L. for us, so both the static `Log` and injecting `ILogger` end up going through Serilog's sinks: https://github.com/discord-csharp/MODiX/blob/master/Modix/Program.cs#L72 .

I don't think we need to necessarily strip out Serilog, as it provides a very extensible configuration model and there are a lot of sinks available. One example would be its "Enrichment" APIs - we can tag log events with data in a contextual fashion, so with our messaging model, that could include data about the event, where it was fired from, the user (if it was discord / the web api), the asp.net core request id (which is added by default, I think), etc - and all of that is included as part of the log event, which can then be formatted in the console or searched in an aformentioned log sink.

**Comment by JakenVeina** [comment]
Yeah consolidating doesn't make sense to me, either. Like @jmazouri said, the Microsoft logging package already abstracts it all away pretty darn well. So long as we're consistent about HOW we log in business code (I.E. use the static `Log` class, or use injected `ILogger<T>`s), changing up the logging strategy is really just a DI config issue, where all we gotta do is attach sinks. Serilog has what looks like a pretty solid set of existing sinks, plus a solid API for writing custom ones (still happy to consider other options). Configuring Serilog to interop with Microsoft's abstractions is as simple as...

```cs
serviceCollection
    .AddLogging(logging => logging
        .AddSerilog());
```

...which is probably pretty much what the `webHostBuilder.UseSerilog()` extension does. I do think it's more appropriate to do it ourselves upon the `IServiceCollection`, rather than the `IWebHostBuilder`, since logging isn't a web-specific concern, but that's a rather picky point.
