### ISSUE TITLE
Re-Applying User Roles on Server Re-Join

### ISSUE THREAD

**Issue by NinjaKitt3n** [discord-csharp/MODiX#443]
When a user leaves currently we have to re-assign the roles on return by:
- Creating a Campaign (with comment)
- Accepting the Campaign (Forced Accept - by Staff)

Would be useful to maintain a list of UserId : RoleId and re-apply the role on rejoin.

@Scott-Caldwell volunteered to take this issue on!

**Comment by Scott-Caldwell** [comment]
Some preliminary thoughts:
* This will likely require a tracking table, something like `GuildUserDepartures`, that maintains records of every instance when a user left a guild and the circumstances around the user's departure (i.e. whether they were kicked, banned, or left freely).

* Additionally, we will probably need another table to track what roles the user had when they left.
  * Question: Should we track and reapply all roles or just rank roles?

* If a user was kicked or banned, their previous roles should not be reapplied if they rejoin the guild.

* Reapplication of roles should not need to go through the promotion system, and so will not generate any promotion history or post any promotion logs or notifications.

* I'm thinking we don't need to set a limit to how high of a rank the bot can reapply, though there are some obvious limitations with the system based on how Discord works. For example, if a Moderator leaves and rejoins, MODiX doesn't even have the permissions to reapply the Moderator rank. Instead, this could be built such that MODiX just applies the highest rank that it has permission to manage to the user (and so the Moderator would automatically be given the Operator rank).

* Question: Should there be a time limit? I.e., if someone leaves and then rejoins a year later, should they still get their previous roles? Or has enough time passed at that point to where we'd want them to have to go through the promotions process to earn back their old roles?

**Comment by JakenVeina** [comment]
> When a user leaves currently we have to re-assign the roles on return by:
> 
> * Creating a Campaign (with comment)
> * Accepting the Campaign (Forced Accept - by Staff)

Why do people continue to think this is true? If you need to apply a role to someone, do it in Discord. The purpose of the campaigns system is to allow the community to vote. If you don't want to allow a vote, you BY DEFINITION do not want to make a promotion campaign.

**Comment by Scott-Caldwell** [comment]
This has been discussed, and it is not something that we are interested in adding.
* It would be a fair amount of work. (Note the schema changes I mention above, and the associated tracking behaviors, in addition to the actual feature itself.)
* The answers to the questions I posed above will necessarily be pretty subjective, and they tend to lend themselves to being handled on a case-by-case basis rather than automatically.
* The return on investment simply isn't there. The effort saved is just a few mouse clicks once every month or two.
