### ISSUE TITLE
Show Command Usage Info Instead of Error

### ISSUE THREAD

**Issue by joshuaedwardcrowe** [discord-csharp/MODiX#445]
I think this error is rather unfriendly and it would be more useful to show them how they could've used the command to get an actual result.

![image](https://user-images.githubusercontent.com/13123486/56149781-35e5b580-5fa5-11e9-8408-6d1e3219d160.png)

**Comment by JakenVeina** [comment]
Agreed. At the moment, this is simply a result of the `Discord.NET` commands system. It generates this error, not us. Need to investigate how/whether the `Discord.NET` commands system can be enhanced to provider better errors, or whether the `CommandResult` it returns contains sufficient information to build a better error message.

**Comment by Scott-Caldwell** [comment]
I agree that this could be a really neat feature, but it looks like this is the extent of the information that we get back from Discord.Net for e.g. `!stack`:

![image](https://user-images.githubusercontent.com/2829282/56218722-712ec580-6033-11e9-86ad-088d78609db3.png)

I'm worried that in order to do this, we'd need to reimplement Discord.Net's `CommandParser` to get information about what the `CommandService` was expecting for arguments vs what it received.

**Comment by Sutarodo** [comment]
It might be worth getting in touch with the Discord.Net developer(s) about this, potentially they have some way to hook into error response?

**Comment by JakenVeina** [comment]
First step would be to ask Monica in Discord. She's the primary dev for that system.

**Comment by thaumanovic** [comment]
These days, the error messages aren't shown. The bot simply reacts with a warning emoji:

![image](https://github.com/discord-csharp/MODiX/assets/30070380/17c7cb4e-220d-447f-aecf-35d0d4f2090b)

It could be useful to add some attributes to each command showing an example usage, but I think a better option would be to simply link to the docs. Perhaps after an arbitrary number (2-3) of failed usages by the same user in certain period.

Thoughts?

**Comment by Scott-Caldwell** [comment]
If you click on the warning emoji to react, it should reply with the error message. But regardless, I'm thinking this will be unnecessary if we migrate everything to slash commands, since slash commands are discoverable and documented within Discord itself
