### ISSUE TITLE
No Claims on Setup

### ISSUE THREAD

**Issue by Sutarodo** [discord-csharp/MODiX#446]
When setting up Modix, no claims are assigned to the tester, meaning they have to assign them all manually.

![No claims assigned](https://i.imgur.com/byTrXPD.png)

Perhaps we could write a little console app to add these claims in the database?

**Comment by Sutarodo** [comment]
Began work on this. Thinking of going ESLint setup-style.

![Setup](https://i.imgur.com/5f0SJex.png)

**Comment by JakenVeina** [comment]
You mean, you instantiated a new database and don't have any claims, yes?

We already have a strategy for seeding the `ClaimMappings` table for new instances. On `GuildAvailable` and `JoinedGuild` if there are no claims at all mapped for that guild, we assume it's a fresh instance or a new guild, and seed the table by assigning all existing claims to every guild role that has the Discord `Administrator` permission. This occurs in `Modix.Services.Core.AuthorizationAutoConfigBehavior`.

If this is not working for you, you're either not an `Administrator` in your test-guild, and the lack of claims is by-design, or it's a bug (I did PR a refactor of this behavior within the past week).

**Comment by Scott-Caldwell** [comment]
I think a utility (or at least a script) like this could have some merit for situations like the Modix Test server, where most people don't have admin permissions.

**Comment by JakenVeina** [comment]
Most people now have admin permissions.

**Comment by Sutarodo** [comment]
I'm happy to scrap this given everyone is given admin permissions on the test server before their instance joins. Otherwise they don't get assigned claims.

**Comment by JakenVeina** [comment]
I adjusted the server to give `Administrator` to `Maintainers`.

If you've got an existing instance that didn't get those claims, just manually truncate the `ClaimMappings` table and launch the bot again. It attempts to seed on every startup.

**Comment by Sutarodo** [comment]
Nice one, closing this.
