### ISSUE TITLE
Moderation improvements

### ISSUE THREAD

**Issue by Scott-Caldwell** [discord-csharp/MODiX#447]
Proposed improvements:
* Remove the ability to permanently mute a user. Instead, if the moderator doesn't provide a time limit, default the mute length to 24 hours.
  * Rationale: It never makes sense to permanently mute a user. If you want to permanently mute someone, you should probably consider just banning them instead.
* Allow users to always rescind infractions that they created, regardless of claims.
  * Rationale: Sometimes people mistakenly create an infraction or create a mute that lasts too long. It would be beneficial to have a way to undo that action without having to enlist the aid of a higher-ranking member.

**Comment by JakenVeina** [comment]
This seems both sensible and doable.

My only extra thought is that the `24 hour` mute setting should probably be configurable, somehow.

**Comment by Foxtrek64** [comment]
Should the self-rescind be duration-limited? Give the user, say 6 hours to catch and make the correction, otherwise it would need to be done by someone with the appropriate claim.

Jumping on board with what Jake said, that 6 hour duration should be configurable.

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
