### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by Trinitek** [discord-csharp/MODiX#45]
I wanted to explore the possibility of porting RoboDanny's `tag` command.

Is there any particular functionality that we need from tags that we don't currently have?

Does the tag ownership model work fine as it is? Tags seem to be owned by individuals, so they're only editable by their creators or staff (?), but we collectively use them in moderation and assisting. Would it make sense to have a pool of server tags and do away with ownership completely?

An option might be to enable the creation of multiple tag pools that are collectively controlled by a particular role. For example, tags popular in the `beginner-questions` channel, like `yellowbook` and `devessentials` might belong to the `help` pool, which can be added to and edited by Associates and higher. There might also be a tag pool called `modtools` with read access restricted to Operators and higher, and so on.

**Comment by Trinitek** [comment]
For reference, I will include the tag command list produced by `?tag help`

```
tag <name>
    Allows you to tag text for later retrieval.
tag alias <new_name> <old_name>
    Creates an alias for a pre-existing tag.
tag all
    Lists all server-specific tags for this server.
tag box
    The tag box is where global tags are stored.
tag claim <tag>
    Claims an unclaimed tag.
tag create <name> <content>
    Creates a new tag owned by you.
tag edit <name> <content>
    Modifies an existing tag that you own.
tag info <name>
    Retrieves info about a tag.
tag list [member]
    Lists all the tags that belong to you or someone else.
tag make
    Interactive makes a tag for you.
tag purge <member>
    Removes all server-specific tags by a user.
tag raw <name>
    Gets the raw content of the tag.
tag remove <name>
    Removes a tag that you own.
tag search <query>
    Searches for a tag.
tag stats [member]
    Gives tag statistics for a member or the server.
```

**Comment by Cisien** [comment]
In the interest of keeping the bot focused on c# moderation, closing
