### ISSUE TITLE
Prevent nominations for Regular when the user joined less than 30 days prior

### ISSUE THREAD

**Issue by jrusbatch** [discord-csharp/MODiX#451]

**Comment by calledude** [comment]
PR it

**Comment by Foxtrek64** [comment]
This sounds like something that should be managed through your server's administrative policy, not through code. Restrict the ability to create nominations to trusted users and tell those users not to create promotions for the user until at least 30 days.

That said, I think it's worth a PR. If we decide we want it, it could end up in some sort of runtime config, like @jmazouri mentioned in Discord. Thought I'd make note of these things here for posterity.
