### ISSUE TITLE
Time in Infractions Footer is Misleading

### ISSUE THREAD

**Issue by Sutarodo** [discord-csharp/MODiX#452]
Infractions footer has a time in it -- this is the time the infractions command was called, not the time the last infraction was recorded.

![image](https://user-images.githubusercontent.com/13123486/56215908-5884d680-6058-11e9-8ac6-e51c2950a8c9.png)

**Comment by Scott-Caldwell** [comment]
We should probably just get rid of that timestamp entirely. It doesn't add anything of value to the embed.

**Comment by Sutarodo** [comment]
Will do it when i get home if nobody beats me to it. :)
