### ISSUE TITLE
Runtime Configuration To-Do List

### ISSUE THREAD

**Issue by Foxtrek64** [discord-csharp/MODiX#467]
Relies on #468 

This is an organizational issue to keep track of active changes that should hook into the a runtime configuration, whether that be stored in the database or in a json/yaml flat file. When an issue is created for a particular item, we'll add it to the entry. If there are any that should tie into this system, create an issue and mention this issue. If it's something worthwhile, we'll add it in. Items below will be checked off as they're merged.

This issue should be closed when this list is complete, not necessarily when the runtime configuration back-end is completed.

| Merged | Issue Description | Issue Number | PR Number |
| :----------: | ---------- | ----------: | ----------: |
| &#9744; | Runtime Configuration | #468 | |
| &#9744; | Promotion Time Restriction | #474 | #545 |
| &#9745; | Service Portal Address | #471 | #476 |
| &#9745; | Now Playing | #472 | #476 |
| &#9744; | Default mute time | #447 | |
| &#9744; | Self-rescind moderation duration | #447 | |

(note to self: checked = `&#9745;`)

Edit: If you want to create a specific entry for this, use the following template:

Title: Runtime Configuration: Description of line item

Body:
```
Discussion item for #467 

This separate issue is opened to keep tabs on discussion for this particular config line item. If this is something deemed worthy, this issue will be added to the first post of #467. Refer to this issue for closing through a PR for this feature.

Lorum Ipsum Long Description
```

**Comment by Foxtrek64** [comment]
Since the system for this already exists and is functional, I'll add this here:

Should we add the various ids and tokens to this list? This should depend on the "available at startup" decision in #468.

**Comment by Foxtrek64** [comment]
In regards to the domain name entry, this is one of the locations it's hard coded. I'm not aware of any others:

![image](https://user-images.githubusercontent.com/7003081/56935476-e16b2b80-6ab6-11e9-9bea-f6e3c387d259.png)

* This should probably not affect users who don't have the pastebin service, otherwise it would break things! Currently I'm running without my own so I'm using `paste.mod.gg`. Perhaps we keep these services as separate configuration items?

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
