### ISSUE TITLE
Announcement System

### ISSUE THREAD

**Issue by Foxtrek64** [discord-csharp/MODiX#469]
This should tie in with the existing restricted mention system, but perhaps a bit differently.

As you can see, I'm trying to use the restricted mention system, but it comes out kind of ugly and as two separate messages. However, as I understand it, the restricted mention system had a different intent, so this is why I'm proposing an addition.

![Example](https://media.discordapp.net/attachments/536023005164470303/572577673239330816/unknown.png)

That said, it appears this may have been an intent with the restricted mention system. The documentation for `!@` shows this:

![Documentation](https://cdn.discordapp.com/attachments/536023005164470303/572577980501458955/unknown.png)

This, to me, reads that it takes a role to mention and a message to append to it and posts that to the channel, perhaps deleting the original message. This is why I tried what I did in the channel above, but this command overload doesn't appear to function as described.

**Comment by JakenVeina** [comment]
So, the intention here is to create a command that takes a `role` and `messageId`, and has the bot replace that message with an identical one, that has the given role mentioned within it.

I don't mean to be harshly critical, especially when code's already been written, but..... this seems heavily like a solution seeking a problem.

You're right that the !mention feature has a specific purpose, which is to allow for more granular control of who gets to mention who, which Discord does not provide. Discord only allows for roles to be mentionable by everybody, or nobody. The !mention command, together with the MODiX Authorization system allows for roles to be mentionable by only certain roles/users, but not everyone.

The only way an !announce command makes any sense is if you expect users to be using the command who aren't already ranked within the guild. Who exactly do you expect to be making announcements to the guild, aside from staff?

**Comment by Foxtrek64** [comment]
>
>
> The only way an !announce command makes any sense is if you expect users to be using the command who aren't already ranked within the guild. Who exactly do you expect to be making announcements to the guild, aside from staff?

If you see the screenshot in the original post, this is the current solution for mentioning users while making announcements. This leaves two messages in the announcements channel, one which is formatted as a command and holds the command text and one which mentions the `News` role, which is my opt-in updates role.

This "works", but is ugly and not the most ideal. Ideally, a staff member would be able to come over to the announcements channel and type `!announce News Some Message` and have it display like this with the original command message remove.d This is how my NewsBot works:
![image](https://user-images.githubusercontent.com/7003081/57005357-1c478f00-6b9d-11e9-9f05-a6451321abbf.png)

NewsBot works in the a similar manner as the current state of the PR works (except for the News role being hard-coded). With NewsBot, a staff member in any channel can type `!announce message` and the NewsBot will enable mentioning the News role, post a formatted message to the announcements channel, and then disable mentioning the News role. Finally, it cleans up the user's command message.

The current state of the PR works similarly, except it accepts the role to mention as an argument and sends the formatted message in the channel the command was run in.

I could invite my NewsBot to every server, but this seems impractical, especially when making announcements is such a common task in most servers. Plus, this requires almost no additional code - just some slight modifications to the MentionService and a new command.

If we wanted to, we could configure an automatic mode, which would allow the user to specify the announcement channel(s) and news role(s) in the config and then just run `!announce message`, just like NewsBot does. However, this is entirely optional; simply convenient.

**Comment by JakenVeina** [comment]
Okay, okay, I'm dumb. I probably just need to go to bed. I basically didn't consider my own fucking point, that even staff cannot just directly mention a news role, or whatever, cause it's not currently configured as mentionable (although, on a separate note, I find it retarded that the setting for this upon a role is named "Allow anyone to @mention this role".

So, with that in mind, yeah, this seems fine.

On the technical side, you need exactly 0 database migration changes. If you want to have a default role and channel, when the user doesn't specify, or if you want to just dump the parameters and only ever have it use the pre-determined role and channel, use the existing `DesignatedRoleService` and `DesignatedChannelService` features.

**Comment by Foxtrek64** [comment]
As a future change, we should look at merging (somewhat) the functionality of the two commands to behave as the following:

`!mention Role` acts the way it does now. Modix just mentions the restricted role.
`!mention Role message` causes MODiX to send an embed with the mention (overriding any designated role) and message, using the bottom part to say who it sent the announce on behalf of.
`!announce message` grabs the mention role from the designations, then does the same as the above.

**Comment by Scott-Caldwell** [comment]
> `!mention Role` acts the way it does now. Modix just mentions the restricted role.
> `!mention Role message` causes MODiX to send an embed, mentioning the specified role and providing the user's message, using the bottom part to say who it sent the command. Deletes the original message.
> `!announce message` grabs the "News" role (or whatever we decide to call it) from the DesignatedRole system, then does the same as `!mention Role message`.

This sounds reasonable to me. The actual mention itself would have to go outside the embed, since pings in embeds don't actually ping anyone.

**Comment by Inzanit** [comment]
The proprosed "future" changes should probably be opened in a new issue, this has been stae since May now, should refresh in a new issue. Reopen if you disagree.

**Comment by Foxtrek64** [comment]
This should be closed anyways. The feature was implemented. Not sure why it had stayed open.

Impl details:

`!announce role message` -- Deletes the user's message and sends a new message with the provided text, mentioning the specified role.
