### ISSUE TITLE
Runtime Config: Promotions

### ISSUE THREAD

**Issue by Foxtrek64** [discord-csharp/MODiX#474]
Discussion item for #467

This separate issue is opened to keep tabs on discussion for this particular config line item. If this is something deemed worthy, this issue will be added to the first post of #467. Refer to this issue for closing through a PR for this feature.

---

[#pull/473](https://github.com/discord-csharp/MODiX/pull/473) ensured that nominations will not be created for users who have not been on the server for at least 30 days. I had a feeling something like this would come up, which is why I remarked at the time that it should be handled by organization policy rather than a hard-coded rule.

That's why, to get the best of both worlds, I'm recommending this be added to the runtime config setting. We need a way to store the minimum duration so it can be configured by communities.

I ran into the following situation: my staff wishes to use the promotions feature for new members. When they join, we create a new promotion for `Member`. Once they reply, staff members will discuss, cast their votes, and approve or deny the promotion to `Member`, allowing the user access to the server.

With the hard-coded 30-day policy, doing so is impossible. As such, we need a way to store this configuration so that it is configurable.

I don't believe we need an explicit on/off configuration - we can just set the minimum duration to 0 if we wish to disable it. The code check would be identical.

**Comment by thaumanovic** [comment]
With the XP-based approach that we have for regular roles, and the removal of time-based requirements for assoc, does this still hold value for us?
