### ISSUE TITLE
Detect users with "invisible" names

### ISSUE THREAD

**Issue by kameko** [discord-csharp/MODiX#487]
It's a minor annoyance that sometimes a user will appear with a username that only contains whitespace unicode characters, making them unpingable.

I have verified `string.IsNullOrWhiteSpace()`/`char.IsWhiteSpace()` detect whitespaces for all the characters in https://en.wikipedia.org/wiki/Whitespace_character which have the "WSpace=Y" property, but it does not detect the characters without the "WSpace=Y" property. These characters are `0x180E`, `0x200B`, `0x200C`, `0x200D`, `0x2060`, `0xFEFF`, which I assume would need to be put into a list and also matched with the username to check if it only contains those characters. MODiX should ideally check every username on boot and from then just rely on to the user joined and user updated events (I forget if this event applies to usernames and not just nicknames)

As to what to do with the user, you could either make an automatic note, auto-rename them, or maybe send them a DM.

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
