### ISSUE TITLE
Marker Roles feature needs naming changes, to eliminate confusion.

### ISSUE THREAD

**Issue by JakenVeina** [discord-csharp/MODiX#494]
E.G.

The role designation should be something like `Subscribable` or `MarkerRole`, not `Pingable`. The role being "pingable" has nothing to do with the functionality that MODiX is providing, and conflicts directly with the Restricted Mentioning feature, which actually DOES make a role functionally "pingable" or not. We've already had at least one third-party user get the config wrong, and come ask us about it.

By extension, all the commands, aliases, and documentations on the module need to be changed.

**Comment by thaumanovic** [comment]
Would be made obsolete by #973
