### ISSUE TITLE
per-role emoji management

### ISSUE THREAD

**Issue by Cisien** [discord-csharp/MODiX#496]
should allow us to carve up our emoji slots by role
each role gets a total number, each person gets a max

for example: associate gets 25 slots, each member gets 1, boosters get 25 slots, each member 1, etc

should also clean up, so if a user leaves the role (boosters, primarily will fall into this) their emoji slots are freed up for others

should also support some way to block the user from using the slots (for example, someone who abuses the emoji slot by breaking the rules)

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
