### ISSUE TITLE
Modix does not properly log infractions for manual bans

### ISSUE THREAD

**Issue by Scott-Caldwell** [discord-csharp/MODiX#504]
There is an existing handler to perform this action. Investigation should be done to determine why the handler isn't functioning correctly.

https://github.com/discord-csharp/MODiX/blob/master/Modix.Services/Moderation/InfractionSyncingHandler.cs

**Comment by Inzanit** [comment]
I assume there's more to this @Scott-Caldwell ? I ran the bot in a test guild and banned an alt, MODiX correctly added a shadow infraction to account for a manual ban?

**Comment by Scott-Caldwell** [comment]
That's the thing; it works *sometimes*. But this functionality has been around for a while, and I've noticed a number of occasions where the infraction still doesn't get created when we manual ban during raids.

**Comment by Rithari** [comment]
Can confirm the following:
- Manual bans and unbans trigger the proper logging of said events;
- Inability to properly replicate the issue, initially the bans did not log, however, after multiple unbans and bans (manual) each and every ban is logging.  

This seems to be the same exact issue as my repository's issue, however, perceived differently than this one's title. Manual bans, from the conducted testing, always log, however, command bans sometimes do and sometimes don't.

D.NET version we've tested: 
2.0.1

**Comment by jhmckimm** [comment]
Is this a symptom of #559 perhaps?

**Comment by Inzanit** [comment]
Are we aware if this is still an issue. I am unsure - we've exclusively used MODiX over the past couple months for bans now. #583 *may* have fixed this?

Personally I'd be good with closing out the issue for now and revisiting if it is still an issue.

**Comment by Rithari** [comment]
After the inability to fix this properly I personally moved to a different approach of handling ban logs - should this still an issue I recommend going for a workaround.

**Comment by Scott-Caldwell** [comment]
The only time I can recall this issue popping up is during raids, and I can't recall really having any since the issue was opened. Nevertheless, it looks like we've done a fair amount of investigating and haven't found any potential culprits, so I'm fine with closing. Can always reopen if we see it happening again.
