### ISSUE TITLE
Username fields on modix website do not ignore trailing whitespaces in the logs tab

### ISSUE THREAD

**Issue by kameko** [discord-csharp/MODiX#509]
When entering a full username in the logs/infractions tab ( https://mod.gg/logs/infractions ) in the Subject or Creator fields with trailing whitespace, no results show up, instead of ignoring/trimming the whitespace. This is especially bothersome since double clicking and copying a username from the Subject or Creator fields seem to append some whitespaces at the end.

Attached is an example:
![image](https://user-images.githubusercontent.com/4977895/60129361-d0f7ca00-9762-11e9-867c-de4fb2fc5234.png)

Also to note is I did not add the whitespaces in that image. As stated above, double-clicking a name to select the text then copying it adds those automatically, so it's kind of a one-two punch thing.

**Comment by kameko** [comment]
Also maybe as a suggestion to turn lemons into lemonade, make the names in the Subject and Creator fields act as links to show only results for that subject/creator. I'm not gonna make an issue for it, but if that sounds interesting to any developers then maybe you could make an issue for it.

**Comment by Sutarodo** [comment]
Don't think we can fix this. We use `vue-good-table` to provide this filtering, so it's either report to them and hope they fix it (or we do) or run a custom solution which could introduce more bugs.

**Comment by jmazouri** [comment]
It is possible to fix, we actually run a custom filterer anyway so it works on username or ID - I'll look into it.

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
