### ISSUE TITLE
Invalid NPM Command in Modix CSPROJ

### ISSUE THREAD

**Issue by Sutarodo** [discord-csharp/MODiX#510]
We have `npm ci`, which will exit with code 1. Changed it back to install and all was good.

![image](https://user-images.githubusercontent.com/13123486/60132062-a9b8f100-9792-11e9-9529-99c1cdeceb01.png)

**Comment by Scott-Caldwell** [comment]
I mean, it's definitely a real thing
<https://docs.npmjs.com/cli/ci.html>

Maybe something weird with node versions or something

**Comment by Sutarodo** [comment]
Im currrently on 8.11.4, is there a reccomended version I should be on? 
![image](https://user-images.githubusercontent.com/13123486/60132984-7aa37f00-9794-11e9-980c-c79e160edc96.png)

**Comment by Scott-Caldwell** [comment]
Looks like the Dockerfile is using 10.x.

This is my current setup, and it works fine for me
```cmd
C:\Users\Scott>node -v
v11.6.0

C:\Users\Scott>npm -v
6.5.0
```

**Comment by jmazouri** [comment]
At least 10.x is required. I've updated [the docs](https://github.com/discord-csharp/MODiX/wiki/Developers) to specify this.
