### ISSUE TITLE
Promotion Commands Missing a Comment Give Vague Error

### ISSUE THREAD

**Issue by joshuaedwardcrowe** [discord-csharp/MODiX#513]
![image](https://user-images.githubusercontent.com/13123486/60342518-93d14900-99a9-11e9-99e3-269d19c9cc3e.png)

Suggesting this is given a reasonable error if not too much effort.

**Comment by Scott-Caldwell** [comment]
Might be tricky to do this. The error message comes from Discord.Net, and the command resolution/error messaging is a bit of a black box. We might be able to get around that by making the comment technically optional and then implementing our own validation logic to throw a meaningful error inside the command.

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
