### ISSUE TITLE
Sanitize Eval input for phone use

### ISSUE THREAD

**Issue by Jay-Madden** [discord-csharp/MODiX#515]
Currently Phones use a different character for quotes, this causes eval to fail on anything requiring/using a string. I propose some sanitation of the eval input for either both strings and string literals or just strings. 
![image1](https://user-images.githubusercontent.com/25359755/61098717-ebea5f80-a42d-11e9-9d18-7f4e882ad93e.jpeg)

**Comment by Gnbrkm41** [comment]
Is this iPhone? I've never seen my phones using smart quotes.

**Comment by JayMaddenCox** [comment]
Yes this is iphone, i wasnt sure if it was ios specific or phone wide

**Comment by Cisien** [comment]
I'm not sure what the issue is, we're returning plain utf8 text. how discord decides to render it is outside of our control.

**Comment by Cisien** [comment]
oh, i see it now, your input text was mangled. Again, not much we can do about it.

**Comment by Jay-Madden** [comment]
Can we not validate the input before it is sent to eval?

**Comment by Cisien** [comment]
What would that get us? We would have to compile the code in the modix process in order to get the same level of detail

**Comment by Inzanit** [comment]
I think this can be closed now?

**Comment by Jay-Madden** [comment]
I suppose so if y'all don't think its an issue, I do still think it would be a very helpful thing to address as right now you cant write some repl code from phones

**Comment by Cisien** [comment]
it's not a repl issue, it's a discord/iphone one.
