### ISSUE TITLE
Feature Request: translate IDs

### ISSUE THREAD

**Issue by HurricanKai** [discord-csharp/MODiX#519]
It can be hard to understand what an infraction means, because an ID is used. These IDs could simply be looked up and info could be displayed in braces behind the id
For example:
`User xxx continued to ask about ToS breaking injector in 143867839282020352`
Modix could turn this into:
`User xxx continued to ask about ToS breaking injector in 143867839282020352 (#general)`
I've seen some people do this by hand already.
For now, just translating Channel IDs is all I'd wish for.
(Of course, this could be extended further to include message IDs (maybe in a format `(date, channel)`)

**Comment by JakenVeina** [comment]
I don't think it's a good idea for MODiX to be manipulating user-entered comments. The idea that people are putting channel ID values in infraction comments is rather absurd to me. Why is that a thing?

**Comment by HurricanKai** [comment]
I think when entering the message in Discord, the channel is used as discord suggests, which will actually send <#ID>. I don't think MODiX should be manipulating user entered comments either, but I think in this case it's worth implementing the same behaviour discord uses, just for ease of use.

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
