### ISSUE TITLE
StarboardService should abort if channel is flagged NSFW

### ISSUE THREAD

**Issue by Foxtrek64** [discord-csharp/MODiX#537]
Currently, based on the current code in the Starboard Service, there is no safety check against adding messages to the starboard which may contain NSFW content.

https://github.com/discord-csharp/MODiX/blob/bc80c0bfcdf4d175819ed7ae2fcfc11477807f0e/Modix.Services/Starboard/StarboardService.cs#L168-L191

Naturally, I feel this is something we might wish to avoid, if only to help other guilds which are running MODiX in production.

As such, I propose adding a quick check at the beginning of the code. Something even as simple as this may work:
```cs
if ((message as SocketGuildMessage).Channel.IsNsfw)
    return;
```
If there is a better place to add this functionality then do let me know.

**Comment by sylveon** [comment]
Why not allow a different starboard for a certain channel designation, and/or the ability to disable starboard for a certain designation?

Combined with automatically designating channels that are marked NSFW, you could have a NSFW-specific starboard or disable stars from NSFW channels easily without hardcoding such a check.

**Comment by Foxtrek64** [comment]
I don't think I'd mind seeing this be configurable. Something within the guild's configuration.

But what do you mean by "designation?"

**Comment by sylveon** [comment]
https://mod.gg/commands#Channel%20Designations

**Comment by Foxtrek64** [comment]
How configurable would you want this? We could add an "NSFW Starboard" designation for the nsfw starboard channel and have it handle for channels that are flagged as NSFW within Discord, but if you want to be able to add more categories than just having a separate nsfw starboard, it would take a bit more redesign work.

**Comment by Inzanit** [comment]
This can be tracked as part of #568
