### ISSUE TITLE
MODiX overrides "Add reaction" permission in mute role

### ISSUE THREAD

**Issue by Inzanit** [discord-csharp/MODiX#552]
Presumably, because the role was created by a bot, any changes made to the Mute role are overridden - not even administrators can change the permissions of the mute role.

In this particular case, the oversight of allowing muted users to add reactions to messages has been left in. Muted users like to spam reactions.

I also could not override the permission on the mute role, MODiX immediately overrode this.

**Comment by Scott-Caldwell** [comment]
At minimum, it would be a good change to always deny the Add Reactions permission to the mute role.

**Comment by Inzanit** [comment]
Resolved
