### ISSUE TITLE
Possible NRE in InfractionSyncingHandler

### ISSUE THREAD

**Issue by jmazouri** [discord-csharp/MODiX#559]
```
System.NullReferenceException

at Modix.Services.Moderation.InfractionSyncingHandler.TryCreateBanInfractionAsync(ISocketUser user, ISocketGuild guild) in InfractionSyncingHandler.cs:line 67
```
https://github.com/discord-csharp/MODiX/blob/d40ad9f3eb8adce2fbc2fa5150fab7943b554bd4/Modix.Services/Moderation/InfractionSyncingHandler.cs#L67

It's possible that `banLog` here is null since we only pull the last 10 audit log records, and if there's a lot of activity the ban could have fallen out of that 10 record window by the time we respond to it. Or, it could be null for some other reason. We should add some null checking here and also decide how to handle it if we can't find an audit log record.

**Comment by Cisien** [comment]
or the rest service didn't receive that audit log entry yet (eventual consistency)

**Comment by Foxtrek64** [comment]
https://paste.mod.gg/uzuzivoquq.sql
Relevant snippet from bot log where this issue caused a bot crash.
