### ISSUE TITLE
View infractions on self

### ISSUE THREAD

**Issue by Paladinleeds** [discord-csharp/MODiX#575]
Allow us a way to view all infractions on our own account through the website. Not sure how it displays them for moderators, but possibly just add a permission to check if the user id is the URL being checked, and if true, mark it as viewable? (Just spitballing ideas here)

**Comment by Inzanit** [comment]
Also consider DM'ing this to the user, giving the user the option.

**Comment by Scott-Caldwell** [comment]
When we do this, we should decide whether to include Notes or not. Unlike other infraction types, they don't necessarily convey anything negative about the subject, and staff aren't compelled to make subjects of notes aware that they were noted.

It's probably mostly harmless to include notes, but I wanted to bring it up for consideration.

**Comment by Rithari** [comment]
I suggest adding the amount of warnings someone has and whether they are active or have decayed. (e.g active = gotten recently, decayed = older )

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
