### ISSUE TITLE
Add user joined/leave logs

### ISSUE THREAD

**Issue by patrickklaeren** [discord-csharp/MODiX#584]
As per functionality from other bots - to fully commit to using MODiX, it might be nice to see users who joined/leave the guild in the assigned moderation log channels.

**Comment by Scott-Caldwell** [comment]
🔗 Related: #226.

**Comment by Emil8250** [comment]
Does it make sense to add these to the moderation log channels? 
And if so, which ModerationActionType should be used? Can't seem to find one that fits join/leave messages.

**Comment by Scott-Caldwell** [comment]
Probably not, moderation log is generally for actions a moderator would perform (warning, muting, banning, etc.) and moderation actions the bot automatically performs (deleting invites, etc.).

We can brainstorm, but my initial thoughts are that we could create a new channel designation type like "UserEventsLog" or something that would include things like join/leave, nickname updates, role changes, etc.

For the C# server, Patrick's [Accord bot](https://github.com/patrickklaeren/Accord) now handles join/leave logs, so this wouldn't be very high priority for us, but it wouldn't be a bad idea to have available in MODiX for other people who want to run MODiX in their own servers.
