### ISSUE TITLE
Add user nickname change log

### ISSUE THREAD

**Issue by patrickklaeren** [discord-csharp/MODiX#585]
As per functionality from other bots - to fully commit to using MODiX, it might be nice to see logs from users who's nicknames have changed in the guild, in the assigned moderation log channels.

**Comment by Scott-Caldwell** [comment]
🔗 Related: #226.

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
