### ISSUE TITLE
Grafana dashboard showing odd values

### ISSUE THREAD

**Issue by mastorm** [discord-csharp/MODiX#589]
Theres something odd in the Guild User Count graph on the grafana dashboard mentioned in #65 
![image](https://user-images.githubusercontent.com/10759336/64281882-704fef00-cf54-11e9-84d1-b9bd53984dcd.png)

**Comment by HurricanKai** [comment]
Try applying `rate(...)` and see if the results are still wrong. Sometimes it just seems that way when looking at absolutes

**Comment by patrickklaeren** [comment]
I believe that graph is showing all-time, which would include those who have left - you can see this number on another dashboard:

![image](https://user-images.githubusercontent.com/1341180/92422657-0f19b780-f176-11ea-8355-4cb38e403a7d.png)

**Comment by patrickklaeren** [comment]
I'll close this out for now and if there is need to revisit it, we can.
