### ISSUE TITLE
User Avatar is missing file extension

### ISSUE THREAD

**Issue by khionu** [discord-csharp/MODiX#60]
When I log in, the source of the image being used for my avatar is `https://cdn.discordapp.com/avatars/96642168176807936/acf8818538bfce80a29793085e46de9c`.

**Comment by jmazouri** [comment]
The actual URL is fine - I can load it when I manually type it into the browser - but I will look into adding the proper extension.

I believe the avatar not loading is a bug related to login caching - we cache the avatar URL as part of the auth token, so if you change your avatar and Discord removes the old one from the CDN, you see a missing image. I think we can implement some basic invalidation / less aggressive caching.
