### ISSUE TITLE
hastebin long code messages?

### ISSUE THREAD

**Issue by nucombo** [discord-csharp/MODiX#600]
Would be really useful if we could tag code messages that are too large with some reaction and the bot would catch that and upload code to hastebin / replace user message with it.

Ideally it would check for the message size before doing so as well(would have to come up with an acceptable length before it accepts doing it).

**Comment by Scott-Caldwell** [comment]
We used to have that exact feature. If a certain number of people reacted to a message with `:tldr:`, and the message was over a certain length (100 characters, I think) the bot would reupload the message to `https://paste.mod.gg/`.

People abused it, and it was annoying. The final straw was when people used it on the guild owner's messages in `#guild-feed`. The feature was removed shortly thereafter.

Our recommendation now is just to politely ask the person to reupload their own code to a paste site. On the upside, this has the benefit of being less jarring to the person whose message is being uploaded, and it accomplishes the whole "teach a man to fish" thing.

**Comment by nucombo** [comment]
@Scott-Caldwell I understand that but can't that be fixed by adding limitations such as only work on channel X and perhaps check for code snippet or certain code keywords?

**Comment by Scott-Caldwell** [comment]
Sure, we can try to put bandages over problems as we think of them, but ultimately I don't think we can fix the root issues of the emoji-based reupload. It's annoying, intrusive, and jarring to the person whose message is being force-reuploaded. It's easy to abuse. It's easy to accidentally trigger. It was rarely used intentionally. It's hard to discover that the behavior even exists.

I really don't want MODiX to get kicked out of the server again. And I genuinely believe that, while it might be tedious to teach new people about paste sites, it's likely the best way to handle things.
