### ISSUE TITLE
!isup command

### ISSUE THREAD

**Issue by nucombo** [discord-csharp/MODiX#601]
Every now and then we see people asking if some website is up, or have the need to check it, works similar to isup.me.

I found this little command something simple and useful, that could be a nice touch to MODiX hence I am suggest it.
```
!isup some.website.com
```

**Comment by Jay-Madden** [comment]
if its agreed upon that this is a wanted feature ill pr it

**Comment by Foxtrek64** [comment]
Isup.me (downfor.io) seems to have an API in the works. We could leverage that when it releases, though I think it may also be adequate just to ping the site. Thoughts?

**Comment by calledude** [comment]
> Isup.me (downfor.io) seems to have an API in the works. We could leverage that when it releases, though I think it may also be adequate just to ping the site. Thoughts?

This _could_ work. However, most sites that have a sane host don't allow ICMP packets through, which would potentially provide you with a false negative, the only real reliable way would be to `GET` whatever domain the user provides as input

**Comment by nucombo** [comment]
@Foxtrek64 you need to actually do an http request, since the domain could be pointing to an IP while not active in the http server

**Comment by Jay-Madden** [comment]
https://isitdown.site/ it seems this could work

**Comment by Foxtrek64** [comment]
> 
> 
> > Isup.me (downfor.io) seems to have an API in the works. We could leverage that when it releases, though I think it may also be adequate just to ping the site. Thoughts?
> 
> This _could_ work. However, most sites that have a sane host don't allow ICMP packets through, which would potentially provide you with a false negative, the only real reliable way would be to `GET` whatever domain the user provides as input

D'oh! You're right. I forgot about that bit. I even wrote a site checker that makes a `GET` request, just grabbing the headers for efficiency.

**Comment by nucombo** [comment]
That smells like a YES to me ;)

**Comment by Foxtrek64** [comment]
As long as @Cisien signs off on it, you're good to go. He's the code owner.

**Comment by nucombo** [comment]
Sorry to disturb you @Cisien if you could provide your pov on this I would appreciate it.

Its a nice little feature, Jay already proposed to do it if accepted, there is an API to leverage the work out, it might not be widely used feature but is useful when needed.

**Comment by Cisien** [comment]
I'm not against it

**Comment by Jay-Madden** [comment]
Well in that case Ill pr it when i get the chance.

**Comment by nucombo** [comment]
Thanks @Jay-Madden awesome job!
