### ISSUE TITLE
All variations to return a path or parent only returns /app

### ISSUE THREAD

**Issue by nucombo** [discord-csharp/MODiX#603]
Not sure if this is a bug or because of how it create the repository, but any variations to get parent or the fullname of a fed path results in /app.

For example:
```cs
!eval Directory.GetParent(@"C:\test\something\file.exe").FullName
```
Or
```cs
!eval new System.IO.DirectoryInfo(@"C:\test\something\file.exe").Parent
```
Just wanted to know if that is right because of the repository or an actual bug.

**Comment by Cisien** [comment]
that would be a framework/scripting thing

**Comment by Cisien** [comment]
![image](https://user-images.githubusercontent.com/4044356/67606325-e2170e80-f735-11e9-99ae-4416e2d82c13.png)

**Comment by nucombo** [comment]
![image](https://user-images.githubusercontent.com/57000940/67610054-90d34300-f766-11e9-9e37-4de532aa4c95.png)

**Comment by Cisien** [comment]
Nope. It might be worth filing an issue in the dotnet repo calling out the discrepancy between Linux and windows

**Comment by nucombo** [comment]
Oh wow, I didn't expect it to be an issue at that end... I don't have any linux to actually test it out to fill a proper issue in there, maybe this weekend I will set one up and do it.
