### ISSUE TITLE
Use Discord Custom Status

### ISSUE THREAD

**Issue by HurricanKai** [discord-csharp/MODiX#604]
Not sure how the API around that is designed, and if it already works with Custom Status Messages,
but once it does, I think it would be nice to display the status using that, removing the `Playing` in front of it

**Comment by GreemDev** [comment]
Last I checked, Custom Statuses are just Rich Presence under the hood; and as it is bots don't have Rich Presence....[but that could change.](https://github.com/discordapp/discord-api-docs/issues/1160#issuecomment-546549711)

**Comment by patrickklaeren** [comment]
As per the issue referenced above it looks like it's a very low priority feature for Discord to implement, if the comments can be believed. If you don't mind I will close this out for now until it becomes viable for bots to do this and we can revisit.

Relevant: discord/discord-api-docs#1160
