### ISSUE TITLE
Tag immediately followed by punctuation fails

### ISSUE THREAD

**Issue by Foxtrek64** [discord-csharp/MODiX#615]
In cases like the following:

"Do you mean $foo?"
"Drop that wall of text into a $paste. It will help keep the chat uncluttered."

Modix ignores the tag being in the text. This is understandable, seeing as `$paste?` is not the same as `$paste`.

We should add a catch in to ignore punctuation when parsing for an inline tag.

**Comment by Scott-Caldwell** [comment]
Seems reasonable. Potential problem is that tag names are allowed to contain punctuation today.

Potential solutions:
1. Disallow punctuation in tag names. Can probably just strip anything from the name that isn't [a-zA-Z0-9] (maybe allow hyphens and/or underscores) when creating the tag. Run a migration that fixes current tag names.
2. Allow punctuation in tag names, and introduce a hierarchy when resolving tag names (e.g. look for tags that contain the punctuation, then look for tags that don't).

Preference is option 1. I don't see a lot of need for punctuation in tag names.

**Comment by Foxtrek64** [comment]
I agree with option 1

**Comment by Scott-Caldwell** [comment]
#632 mostly fixes this by ignoring any trailing punctuation when attempting to use an inline tag. We should apply the same rules when creating and modifying tags and using them with the `!tag tagname` command.

Note: We currently don't have any tags that end in punctuation, so fixing existing records is likely not necessary.
