### ISSUE TITLE
DiscordSerilogAdapter seems to not receive log events from the Web Request pipeline, only from the Bot Request pipeline

### ISSUE THREAD

**Issue by JakenVeina** [discord-csharp/MODiX#631]
This is gonna need some investigation, as everything SEEMS to be setup properly.

The only thing I spot that's out of place is that `LoggerConfiguration` is being built and injected into Serilog via the `static class Log` API, within `Main()` in `Program.cs` outside of the context of the Web Request pipeline. This should probably be moved inside the call to `.UseSerilog()` farther down within the file, which has an overload that takes a `LoggerConfiguration` builder delegate.

If that doesn't do it, I dunno. Errors during web requests definitely make it into the rolling log file, but not into the #modix-log channel.

**Comment by NullEntity** [comment]
I wasn't able to reproduce this. My Modix instance didn't have correct permissions and web requests that caused permission exceptions were correctly logged to the webhook.

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
