### ISSUE TITLE
Ability to remove !info embed

### ISSUE THREAD

**Issue by Schakal-Wilhelm** [discord-csharp/MODiX#639]
I demand ":x:" reaction to be applicable (and functional) to embedded posts which display information about the user, invoked by !info command.

**Comment by Jay-Madden** [comment]
to be honest this is a really easy thing to add and a great first issue. If you pulled the repo and PRed it it would probably be quickly approved.

**Comment by Schakal-Wilhelm** [comment]
I don't think I'm capable of performing such an act, but I will certainly try.

**Comment by Cisien** [comment]
i'm pretty sure all it is, is calling an extension method on the embed builder

**Comment by Schakal-Wilhelm** [comment]
Thanks Fred. You guys can apply `ModixContributor` role to my profile any time now. I'll be checking to see when it's up.
