### ISSUE TITLE
StackExchangeModule does not valid exchange token for null

### ISSUE THREAD

**Issue by 333fred** [discord-csharp/MODiX#643]
If the token is null, it's silently used. It will then cause a WebException in the StackExchangeService when the query fails due to lack of token.

**Comment by Inzanit** [comment]
Little confused, I can't see the exception, though MODiX comes back with a more or less empty embed. 
![image](https://user-images.githubusercontent.com/1341180/72019901-720f2380-3262-11ea-9729-7365ec507e3e.png)

**Comment by 333fred** [comment]
@Inzanit but I'm assuming you also didn't get any logs about said empty token?

**Comment by 333fred** [comment]
I would guess something else in the module will catch the exception and format as an empty message?

**Comment by Inzanit** [comment]
Logging it at warning level would probably be good enough UX for developers. I didn't see any exception being raised, even with all exceptions turned on - maybe I'm missing something, I assume you just ran the command, nothing special?

Beyond logging, we could also return an actual error message in the Discord chat to inform users that there is no valid key.

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
