### ISSUE TITLE
Docker build fails when checked out with Windows line endings

### ISSUE THREAD

**Issue by NullEntity** [discord-csharp/MODiX#646]
A few people have gotten the following error: https://media.discordapp.net/attachments/536023005164470303/664298874176798731/unknown.png

This seems to happen when build.sh is using Windows line endings. I have no idea if the issue affects more files than just the .sh scripts.

**Comment by Cisien** [comment]
We don’t have a .gitattributes that handles this?

**Comment by NullEntity** [comment]
It doesn't handle this. I think updating it to say .sh files use Unix style line endings could fix it.

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
