### ISSUE TITLE
Grafana Dashboard

### ISSUE THREAD

**Issue by mastorm** [discord-csharp/MODiX#65]
Insights on:
- Node memory usage
- Messages processed

**Comment by NinjaKitt3n** [comment]
You could add a lot more to this:
- Infractions issued / types / severity
- REPL usage
- Command counts
- Process Errors

**Comment by Inzanit** [comment]
Believe @Cisien has this set up

**Comment by Scott-Caldwell** [comment]
🔗 https://modix-grafana.cisien.com/
