### ISSUE TITLE
Modix should check if it has permission to modify roles

### ISSUE THREAD

**Issue by Cisien** [discord-csharp/MODiX#653]
https://paste.mod.gg/hexoyemebi.json

It's currently attempting to set permission on channels it doesn't have permission to set permissions on (archived channels), which is causing forbidden api responses; which I suspect contributed to yesterday's outage.

Specifically in this case, modix should check if it has the right perms, but I think this is an area that can be more broadly improved to avoid getting on discord's bad side.

**Comment by Scott-Caldwell** [comment]
I feel like we should still log the errors, in case it's a situation where Modix is meant to be able to modify the channel but the permissions are messed up. So I can agree, that's a change we ought to make: check whether we have permissions and log an error if we don't.

The "right" way to keep Modix from continually attempting to set up mute roles and such on archive channels is just to set the channels as Unmoderated.

**Comment by Scott-Caldwell** [comment]
There might be value in extending channel designations so that we can make entire categories (e.g. Archive) Unmoderated, so we don't have to remember to update channel designations every time we archive a channel

**Comment by JakenVeina** [comment]
I think the conclusion is we'll enhance designations to account for categories, like Scott suggested. This is tracked by #699. If no one else objects, I'm going to close this.
