### ISSUE TITLE
infractions with severity

### ISSUE THREAD

**Issue by Cisien** [discord-csharp/MODiX#66]

**Comment by JakenVeina** [comment]
Sooo..... what about this?

**Comment by NinjaKitt3n** [comment]
I think this works quite well in conjunction with #74 

It's a system that's quite well adopted for things in real-life also (points on driving license, for example).

Some key decisions need to be made - although these could be configurable(s)?
- What are the levels of severity & how many `penalty points` would each carry?
- re #74 What is the level of decay =>how many points are deducted over how long? (does incurring more points reset the decay timer?)
- How will the severity levels be split in whom can issue, for example warnings can be issued by a lower ranking role than a mute for example (in current set-up).

**Comment by JakenVeina** [comment]
Like #74, I just don't see the practical value.

Do any of the mods anticipate reading a list of infractions upon a user, and caring about "severity" over just reading the "reason" comment?

**Comment by NinjaKitt3n** [comment]
Well, there's more than just a human aspect to this - automating punishments, etc.

As a human, I'd be more likely to read a reason for something, as an automated system I'd prefer to add up some numbers to establish how bad a user I'm dealing with. I suppose it depends on what the end-goal/vision for this is.

**Comment by Cisien** [comment]
yeah, that's pretty much the idea. Maybe in the future instead of having someone make the call to ban, the bot will auto-ban when enough points have been accumulated.

**Comment by Cisien** [comment]
the other thought is something like a heavy warning, or a light warning. (second warning carries more weight than the first one, for example)

**Comment by Trinitek** [comment]
I definitely don't like the idea of auto-banning.  Sometimes two operators will issue two warnings at the same time by mistake; what if that triggers an auto-ban?  If the bot could instead post a suggestion to ban/demote when a user is warned, that would be fine.

Also, I feel like splitting warnings between light and heavy versions would be a useless distinction.  Tempmutes act as heavy warnings already, and we also have `note`s for non-warnings.

**Comment by jmazouri** [comment]
This doesn't seem to have much push, and the !note infractions we added after this was proposed in conjunction with !warn seem to cover most of our use cases. Closing for now.
