### ISSUE TITLE
Refactor data layer to make use of `IEntityTypeConfiguration<TEntity>`

### ISSUE THREAD

**Issue by Inzanit** [discord-csharp/MODiX#668]
Currently there is a custom implementation to provide Entity Framework with model builders per entity, with an `OnModelCreating` attribute.

This can now be subsituted with the built in `IEntityTypeConfigration<T>` interface and functionality to load all configurations in an assembly.

i.e.

```cs
modelBuilder.ApplyConfigurationsFromAssembly(typeof(ModixContext).Assembly);
```

Would be in the `OnModelCreating` method of `ModixContext`.

Followed by changes to all entity models where they would now contain a configuration class:

```cs
public class TagEntityConfiguration : IEntityTypeConfiguration<TagEntity>
{
    public void Configure(EntityTypeBuilder<TagEntity> builder)
    {

        builder
            .Property(x => x.GuildId)
            .HasConversion<long>();

        builder
            .Property(x => x.OwnerUserId)
            .HasConversion<long>();

        builder
            .Property(x => x.OwnerRoleId)
            .HasConversion<long>();

        builder
            .HasOne(x => x.CreateAction)
            .WithOne()
            .HasForeignKey<TagEntity>(x => x.CreateActionId);

        builder
            .HasOne(x => x.DeleteAction)
            .WithOne()
            .HasForeignKey<TagEntity>(x => x.DeleteActionId);

        builder
            .HasOne(x => x.OwnerUser)
            .WithMany()
            .HasForeignKey(x => new { x.GuildId, x.OwnerUserId });

        builder
            .HasOne(x => x.OwnerRole)
            .WithMany()
            .HasForeignKey(x => x.OwnerRoleId);

        builder
            .HasIndex(x => x.GuildId);

        builder
            .HasIndex(x => x.Name);

        builder
            .HasIndex(x => x.OwnerUserId);

        builder
            .HasIndex(x => x.OwnerRoleId);
    }
}
```

I propose that entity type configuration classes are defined in the same file as the entity model itself, size dependent, as this makes configurations clearer.

Following models need to be refactored:

- [x] `ClaimMappingEntity`
- [x] `ConfigurationActionEntity`
- [x] `DesignatedChannelMappingEntity` #678 
- [x] `DesignatedRoleMappingEntity`
- [x] `GuildChannelEntity` #678 
- [x] `GuildRoleEntity`
- [x] `GuildUserEntity` #678 
- [x] `MessageEntity` #678 
- [x] `UserEntity`
- [x] `EmojiEntity`
- [x] `DeletedMessageBatchEntity`
- [x] `InfractionEntity`
- [x] `ModerationActionEntity`
- [x] `PromotionActionEntity`
- [x] `PromotionCampaignEntity`
- [x] `PromotionCommentEntity`
- [x] `TagActionEntity`
- [X] `TagEntity` #669

**Comment by Inzanit** [comment]
Following models need to be refactored:

- [ ] `ClaimMappingEntity`
- [ ] `ConfigurationActionEntity`
- [ ] `DesignatedChannelMappingEntity`
- [ ] `DesignatedRoleMappingEntity`
- [ ] `GuildChannelEntity`
- [ ] `GuildRoleEntity`
- [ ] `GuildUserEntity`
- [ ] `MessageEntity`
- [ ] `UserEntity`
- [ ] `EmojiEntity`
- [ ] `DeletedMessageBatchEntity`
- [ ] `InfractionEntity`
- [ ] `ModerationActionEntity`
- [ ] `PromotionActionEntity`
- [ ] `PromotionCampaignEntity`
- [ ] `PromotionCommentEntity`
- [ ] `TagActionEntity`
- [X] `TagEntity` #669

**Comment by Scott-Caldwell** [comment]
Completed as of #717.
