### ISSUE TITLE
Remove redundant XML documentation noise

### ISSUE THREAD

**Issue by patrickklaeren** [discord-csharp/MODiX#672]
I appreciate the need for documenting code, however I feel some of MODiX has lost the spirit of what is considered a good comment. If we are to show off MODiX, the current format of XML documentation on all members is fairly noisy.

MODiX isn't a library or framework that has to explain every detail or implementation and a lot of it is self explanatory.

It would be good to discuss the removal of the documentation that doesn't serve a purpose, i.e.:

```cs
/// <summary>
/// Retrieves the user, if any, associated with the given user ID.
/// </summary>
/// <param name="userId">The Discord snowflake ID of the user to retrieve.</param>
/// <returns>
/// A <see cref="Task"/> that completes when the operation completes,
/// containing the user identified by the supplied ID.
/// Returns <see langword="null"/> if no such user was found.
/// </returns>
Task<IUser?> GetUserAsync(ulong userId);
```
Could become more digestible and readable with:
```cs
Task<IUser?> GetUserAsync(ulong userId);
```
The method name is self documenting, the parameter name is well formed and the nullable `IUser?` return type gives consumers in their own codebase a good example of how this method works.

This is especially prevalent in the entity model classes:

```cs
/// <summary>
/// A unique identifier for this mapping.
/// </summary>
[Required, Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
public long Id { get; set; }
```
Could be
```cs
[Required, Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
public long Id { get; set; }
```

**Comment by JakenVeina** [comment]
The intention when I wrote this was basically "There are some things that could use a description of what the hell they are, and how they work. Yeah, not everything needs it, but XML docs should be complete. There are few things I hate more than going to a project's docs page and seeing that some method or property has no docs at all."

In retrospect, we don't publish XML docs. Any really critical information that's not inferrable from context can be either a regular comment, or described in an appropriate article on GitHub. I'm fine with dumping almost all of these, as we go.
