### ISSUE TITLE
Discuss development instance deployment

### ISSUE THREAD

**Issue by patrickklaeren** [discord-csharp/MODiX#673]
Make more use of the MODiX development server, and add a development instance of the bot, that pulls from `dev`, rather than us just deploying straight to `master`.

Not sure what is involved here or if we have the infrastructure for @Cisien to host an extra instance. Can help out in that regard, but I'm not sure how or where there should be considerations.

**Comment by Inzanit** [comment]
Looks like `dev` is fairly far behind `master` at this point, could consider either PR or just flat out rebasing it.

**Comment by JakenVeina** [comment]
Rather than `dev`, perhaps it should be `stage`, if its purpose is to stage stuff before deployment. And yeah, if it's something we keep running in the test-server that could give us more real data to test migrations and queries against.

Regarding the `dev` branch... is there even anything IN there that we care about?

**Comment by NullEntity** [comment]
Is branching the right thing to be using here? Sounds like we want to first roll out any given release to the stage environment, then once it's tested promote it to prod.

**Comment by Inzanit** [comment]
I would like to think branching is the right thing to do here - merge something into `stage`, or whatever we end up calling the branch, once happy, `stage` can get merged into `master` and deployed. Meanwhile `master` can just live on its own.

**Comment by madman2021** [comment]
I agree with having `Master` as the known working / Live branch, leaving `dev`/`stage` to the pre-production testing.

**Comment by patrickklaeren** [comment]
I'll close this out for now and we can revisit if the need arises - the test server seems to be doing fine for now.
