### ISSUE TITLE
Discuss: Moving Forward: Community Collaboration, and v2

### ISSUE THREAD

**Issue by JakenVeina** [discord-csharp/MODiX#682]
Ideas for what to focus on, going forward, per discussion among myself, @Inzanit, @Scott-Caldwell, and @jrusbatch.

1. Everyone needs to be more diligent about having design discussions in GitHub, or at least summarizing relevant bits in GitHub, after the fact. A good chunk of all the miscommunication we've had lately can be attributed to different people having different expectations about different lines of communication. Discord is certainly a lot better for having dynamic conversations, and for discussing specific technical issues, but if it's not documented in GitHub, you can't reasonably expect the rest of the MODiX community to be up-to-speed on what's going on, and where proposals and issues stand.

2. The MODiX community spans the globe, and is no-one's primary job. There are very few community members whose schedules line up with each other. As such, we should all try to be understanding when receiving, or needing to provide, gentle reminders about outstanding issues. However, we probably would value from some general guidelines on how often members should be expected to contribute, read through active issues and PRs, perform reviews, etc. This mainly applies to "maintainers", at term which could also use some sort of definition. There's definitely a risk of discouraging contributors, rather an encouraging, if this is not done well, so it should be throughly discussed among the entire community.
 
3. We need to do what we all agreed needed to happen a year ago, but which no one (myself in particular) has bothered to actually do: write documentation. This includes things not self-documented or easily inferred from the codebase, like what the various application layers are, what purpose they serve, how they're intended to interact with each other, what the general featuresets of MODiX are, how they interact, etc. Most importantly in this will be updates/enhancements to the "How to contribute to MODiX" page, to include not just info about how to get the bot to compile, but some general steps and guidelines about how you would go about implementing a new feature, or enhancing an existing feature.
 
4. We need to make the MODiX codebase more approachable to a wider community of potential contributors, and where point 3 does not address this, refactoring should be considered. Proposals for refactoring are subject to the same considerations as all proposals and PRs: they should seek to perform the same functional/design goals as the the code affected, or should involve discussion of why the functional/design goals should change. And in both cases, input from the community should be expected.

Also, @Inzanit has setup some Issues for discussing and implementing specific refactors that have already been agreed on, relevant to point 4. above, and create the "v2" Project to help track them.

Thoughts and input are welcome.

**Comment by NullEntity** [comment]
I'd like to see a curated current sprint so I know what's important to help with. Looking at all the issues to try and figure out what's most useful is a bit overwhelming.

**Comment by Inzanit** [comment]
I think we should also make a point of containing more code/repo-based discussion in GitHub?

**Comment by JakenVeina** [comment]
Yeah, that's basically the idea of Point 1. Discussions should either happen here, or should be summarized here, after-the-fact (technical discussions can certainly be a lot more efficient in Discord).

**Comment by JakenVeina** [comment]
Last chance for any commenting from the community, before I close this out and start writing docs and guides based on these ideas.
