### ISSUE TITLE
MODiX should check for permission before trying to add reactions

### ISSUE THREAD

**Issue by Scott-Caldwell** [discord-csharp/MODiX#702]
https://paste.mod.gg/qikoriyuha.json

Above occurred while trying to add the confirmation checkmark to a mute command in a channel that does not allow reactions.

**Comment by JakenVeina** [comment]
What channel? Do we really need to support MODiX being active in channels that are (at least partially) restricted?

**Comment by Scott-Caldwell** [comment]
This was in #meta, which does not currently allow reactions
