### ISSUE TITLE
!time command

### ISSUE THREAD

**Issue by reflectronic** [discord-csharp/MODiX#708]
Sometimes, it could be useful to see the local time of other members on the server (e.g. you may want to know if someone is available). I propose some sort of time functionality, where one can register themselves into a certain time zone, and others can request the the time at a certain member's location. For example:
```bash
!settz -5 # Sets my time zone to UTC -05:00
!settz EST # Will also set time zone to UTC -05:00
```

```bash
!time reflectronic # 🕝 Tuesday, February 11, 2020 at 1:33:52 AM
```
Open questions:
- How should we deal with daylight savings time? (Generally time is hard to get right, and it may just be acceptable to just require it be manually adjusted.)

**Comment by Gnbrkm41** [comment]
> Daylight saving time

What if we store [one of those](https://en.m.wikipedia.org/wiki/List_of_tz_database_time_zones) instead of explicit UTC offset so the bot can account for DST as well?

**Comment by JakenVeina** [comment]
> > Daylight saving time
> 
> What if we store [one of those](https://en.m.wikipedia.org/wiki/List_of_tz_database_time_zones) instead of explicit UTC offset so the bot can account for DST as well?

Seems like the obvious answer, from the get go. Timezones != offsets. If we want timezones, we use timezones, not offsets.

How about we provide roles that users can self-assign that designate their timezone, rather than requiring use of a command?

**Comment by ProIcons** [comment]
If a user provides their timezone couldn't TimeZoneInfo.IsDaylightSavingTime could be used?
https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo.isdaylightsavingtime?view=net-5.0

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
