### ISSUE TITLE
Remove TypeScript enums for channel and role designations

### ISSUE THREAD

**Issue by Scott-Caldwell** [discord-csharp/MODiX#709]
It's a bit unnecessary to have to maintain our designation types in two separate locations (the enums in `Modix.Data` and the enums in the web frontend). Thinking we should remove the TypeScript enums and use the `Modix.Data` enums as the source of truth.

- `Modix/ClientApp/src/models/moderation/ChannelDesignation.ts`
- `Modix/ClientApp/src/models/moderation/RoleDesignation.ts`

**Comment by JakenVeina** [comment]
How do we implement this though? Are the enums in TypeScript used as a "source of truth" or are they used to safely refer to specific designations within code? I.E. we can remove the enums if they're only referenced as...

```ts
for(let designation of RoleDesignations)
```

...but not if they're referenced as...

```ts
RoleDesignation.CountsTowardsGuildParticipation
```

**Comment by Scott-Caldwell** [comment]
I think they're only used to determine what tabs to show on the config page. We shouldn't be doing any logic specific to any particular designations from the web frontend.

**Comment by jmazouri** [comment]
I'll be addressing this in a PR soon
