### ISSUE TITLE
Gracefully handle !clean requests for old messages

### ISSUE THREAD

**Issue by Scott-Caldwell** [discord-csharp/MODiX#711]
Discord's bulk message delete API won't delete messages older than 2 weeks and will throw an error if you try. It might be nice to limit the messages we try to delete with `!clean` to messages within the past 2 weeks so that we don't end up bumping into that error.

**Comment by Cisien** [comment]
what if we fall back to the non-bulk api if older than 2 weeks, and just slowly churn through the messages until done?

**Comment by FiniteReality** [comment]
Discord doesn't like that, AFAIK. The best option IMHO would be to filter the message IDs based on whether their snowflake is greater than or equal to this:
```cs
var minimum = SnowflakeUtils.ToSnowflake(DateTimeOffset.UtcNow.Subtract(TimeSpan.FromDays(14)));
```

**Comment by JakenVeina** [comment]
Discord doesn't like deleting old messages?

I'm guessing this is in reference to deleting an archive channel?

**Comment by FiniteReality** [comment]
@JakenVeina This is in reference to deleting messages from any channel where the message is older than two weeks.

The restriction was put there in the first place because it was slowing down their database queries - I imagine deleting a single message does the same thing, but much slower.

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
