### ISSUE TITLE
Add infraction creator to infractions embed

### ISSUE THREAD

**Issue by Foxtrek64** [discord-csharp/MODiX#712]
Currently, infractions display as such:

![Current](https://cdn.discordapp.com/attachments/536023005164470303/677971657192898590/unknown.png)

We should add modify the format to match the following to better match the view provided by the web interface:
`{icon} {type} - Created by {user} at {date}`

**Comment by Scott-Caldwell** [comment]
Seems reasonable. Nitpick: I think "on" instead of "at" sounds slightly better
