### ISSUE TITLE
decaying infractions

### ISSUE THREAD

**Issue by Cisien** [discord-csharp/MODiX#74]
infractions expire over time. different infractions have different weights

**Comment by JakenVeina** [comment]
Do we want to have gradually decaying weights, or just have weights be zeroed-out for expired infractions?

I'm partial to the latter. I don't think this idea needs to be terribly complicated. The only uses I can think of for such a feature are A) a users infractions can be sorted by weight, and B) we can calculate a "total infraction score" for each user. Honestly, neither of these seem like they have much practical value to me.

Do we really anticipate having to deal out so many infractions that we need such a sophisticated sorting mechanism? Or that we need some calculated score to tell us when it's time to ban someone?

**Comment by Trinitek** [comment]
A linear decay function is simple enough; once the weight hits 0, the "expired" flag is set.

That's what we're trying to get at with the idea of decaying infractions anyway, right?  That we gradually forgive warns and mutes as time passes until it's forgiven completely?

**Comment by JakenVeina** [comment]
That makes sense, I just think it's over-complicated for our needs.

**Comment by thaumanovic** [comment]
This could still be useful as a general MODiX feature for other guilds, but I don't see it bringing much value to the C# server specifically as moderation action seems to be at the discretion of staff and the context surrounding each infraction.

While it could introduce "fairness" to enforce some sort of consistency (e.g. 3 warns = you get banned), I personally don't think moderation is ever that straightforward.

I'll suggest that this issue be closed for these reasons.

**Comment by Scott-Caldwell** [comment]
I think I'd agree. In practice, we take into consideration how long ago old infractions occurred and how frequent they were anyway, and hiding old infractions by decaying them might just end up removing useful historical context.

I'll close this for now, but we can reopen if staff really want this feature.
