### ISSUE TITLE
Consider adding some data/privacy tools for users in MODiX...

### ISSUE THREAD

**Issue by Perksey** [discord-csharp/MODiX#748]
...by allowing users to **download data** and allow users to **delete their data** (at the cost of kicking them from the server to ensure that no further data is collected by MODiX - obviously Discord will still have data from them)

**Comment by Cisien** [comment]
@JakenVeina doesn't modix already hook the user left event and delete the records? if not, it should (except infractions).

**Comment by JakenVeina** [comment]
Doesn't look like it, no.

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
