### ISSUE TITLE
Consider making the jump link in Message links more visible

### ISSUE THREAD

**Issue by Jay-Madden** [discord-csharp/MODiX#749]
On my server there has been a lot of confusion about how to actually jump to a linked conversation. I propose that we somehow make it clear that this is a hyper link.
![image](https://user-images.githubusercontent.com/25359755/79917462-87b2ee00-83f8-11ea-8e33-e3ab6e122447.png)

**Comment by Nathan-Binkley** [comment]
Maybe a instead of "#general-chat" it says "Jump to Message in #general-chat"???

**Comment by JakenVeina** [comment]
You beat me to it. I had this same thought today.

Maybe `#general-chat (click here)`?

**Comment by Jay-Madden** [comment]
That works, anything that makes it clear like "hey this is a thing you can click"
