### ISSUE TITLE
Admin Commands - Infractions

### ISSUE THREAD

**Issue by Cisien** [discord-csharp/MODiX#75]
infractions search
infractions remove

**Comment by JakenVeina** [comment]
Regarding the "remove" command:

Should the command delete infractions entirely, or just force them to expire? I'm thinking the latter, in which case the followup is: How much should we track changes to infractions? Should we just add an UpdatedBy field, in addition to CreatedBy, to keep track of the last person to change it? Or should we keep a separate log table for all moderation actions?

**Comment by Trinitek** [comment]
I think a special "rescinded" flag would be preferred to distinguish between infractions that expired naturally and ones that were removed, but would be functionally equivalent to "expired".  Then, when listing a user's infractions, we could provide a flag parameter to either show or hide those that were rescinded.

For the sake of completeness, I would prefer to have a full log table--although actions are logged to the message-log channel, so that may not be necessary.

**Comment by JakenVeina** [comment]
I forgot about the channel.

I feel like there's value in doing both. If only because a table is more easily searchable.

**Comment by mastorm** [comment]
What if we introduce tags for infractions? %warn [major] Constant spam
So deleting can just be a [inactive] tag.

**Comment by JakenVeina** [comment]
Initial draft of Infractions architecture: https://github.com/JakenVeina/MODiX/commit/0a7d0e409641f3ad15ad5b37e77f153719539337

Also, gutting existing moderation/admin/db stuff: https://github.com/JakenVeina/MODiX/commit/fb02a5a7989fb97aafff0fcb51171c782a59e2e2

**Comment by johnbouma** [comment]
Pretty much the same architecture here - was able to leave more of the existing code intact.  See if you can pull anything out of it,

https://github.com/johnbouma/MODiX/commit/a0988622c61fd44fd9267822d0ea9df75a41a7ca
https://github.com/johnbouma/MODiX/commit/a1a51f530c4c8eea76635a3f71bffe64fcc77365

**Comment by mastorm** [comment]
We dont want to leave existing code intact. The existing code is ready to be thrown out of the window

**Comment by JakenVeina** [comment]
The only thing that worries me is that there are a bunch of dependencies in GuildConfigModule that lead back to the existing DB classes/services. Can someone confirm if that module is safe to dump, or go in and break the dependencies?

**Comment by Cisien** [comment]
safe to dump
it was going to be used for configuring things like which roles can do what, etc
