### ISSUE TITLE
LINQ not being translated to SQL properly

### ISSUE THREAD

**Issue by Scott-Caldwell** [discord-csharp/MODiX#756]
https://paste.mod.gg/gikufucojo.json

To reproduce:
1. Go to the site -> Logs -> Deletions
1. Type "test" in the Content search box in the column header

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
