### ISSUE TITLE
NullReferenceException while attempting to update a tag

### ISSUE THREAD

**Issue by Scott-Caldwell** [discord-csharp/MODiX#757]
https://paste.mod.gg/guvironefi.json

Command used was:
```
!tag update randomdiceroll 1488944457420413255478064584723979166030262739927953241852712894252132393610644753103099711321803371747528344014235875600519
```

The tag does exist, but the user executing the command does not own the tag.

**Comment by Jay-Madden** [comment]
I have had a similar bug on my server. except users without the modify tag perm have been able to delete tags they don’t own
