### ISSUE TITLE
Censor invite links

### ISSUE THREAD

**Issue by Cisien** [discord-csharp/MODiX#76]

**Comment by Inzanit** [comment]
I'll take this one, if no one else has

**Comment by JakenVeina** [comment]
Are we talking about censoring links to other guilds, posted in our guild?

**Comment by Inzanit** [comment]
Same functionality as Rowboat has currently - so yes. Anyone <= Associate has invite links purged, but this will link with #32 to be configurable.

**Comment by jmazouri** [comment]
Closed as of #92
