### ISSUE TITLE
Coding/Styling/Formatting Standards - Discussion Hub

### ISSUE THREAD

**Issue by JakenVeina** [discord-csharp/MODiX#79]
See title.

**Comment by Cisien** [comment]
My proposal is to follow the MS conventions doc
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions

**Comment by JakenVeina** [comment]
Opinions on `MyMethod()` vs `MyMethodAsync()` for methods that are meant to be `await`ed?

**Comment by JakenVeina** [comment]
From an in-Discord conversation somewhere, I believe we basically decided to not `throw new ArgumentNullException` within dependency-injected constructors, yes?

**Comment by JakenVeina** [comment]
Opinions on 
```csharp
[AttributeA, AttributeB]
```
vs
```csharp
[AttributeA]
[AttributeB]
```

I myself much prefer the second one, as it follows a more general rule of "one logical thought per line". It also makes it much easier to comment out attributes during debugging.

**Comment by Inzanit** [comment]
From here, I think any other style discussions could have their own issue, seems pretty set now.
