### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by JakenVeina** [discord-csharp/MODiX#80]
Vote now for your preferred unit testing frameworks!

I'm partial to setups including NUnit + NSubstitute + Shouldly.

**Comment by Trinitek** [comment]
I use NUnit personally.  I don't have experience with any others.

**Comment by JasonHughes94** [comment]
I normally do - NUnit and TestStack.bddfy

**Comment by Inzanit** [comment]
Let's get Rowboat replaced, first.

NUnit would be my favourite. Along with Shoudly and AutoFixture.

**Comment by mariocatch** [comment]
Prefer Moq for the mocking over NSubstitute personally.

**Comment by NullEntity** [comment]
I use NUnit and Moq. I'm pretty willing to change to XUnit. I prefer Moq over NSub, but I don't have much experience with NSub. And I love AutoFixture and auto mocking frameworks.

**Comment by Crowes** [comment]
NUnit and Moq.

**Comment by Inzanit** [comment]
Frameworks in place now, closing this off
