### ISSUE TITLE
Ignore commands containing only '?'

### ISSUE THREAD

**Issue by spixy** [discord-csharp/MODiX#806]
*Somebody:* `??`
*Modix:* `Error: UnknownCommand, Unknown command.`

### Proposition:
Ignore commands containing only `?` characters, aka `^[?]+` (regex).

**Comment by Scott-Caldwell** [comment]
This is a bug in [modix-translator](https://github.com/discord-csharp/modix-translator), not MODiX. I don't seem to have permissions to transfer issues there, though

**Comment by spixy** [comment]
Oh right, and it just reuses Modix token. I created new issue there.
