### ISSUE TITLE
Don't invoke tags that are embedded inside code blocks

### ISSUE THREAD

**Issue by Scott-Caldwell** [discord-csharp/MODiX#808]
For example, if someone is sharing some PowerShell code like
```powershell
$code = "whatever"
```
it'll unintentionally trigger the $code tag.

We should look into ignoring inline tags that are inside of code blocks.

**Comment by Shidesu** [comment]
As discussed on the discord I'd like to try to work on that issue (Kao#2541)

**Comment by Scott-Caldwell** [comment]
Thanks! I've assigned this issue to you
