### ISSUE TITLE
Online Member Count Returns 0

### ISSUE THREAD

**Issue by Hamsterland** [discord-csharp/MODiX#815]
https://github.com/discord-csharp/MODiX/blob/07ab7dc2ac81ecc3193bbf749862704594a8d0da/Modix.Bot/Modules/GuildInfoModule.cs#L153

Looks like the `serverinfo` command shows that there are always 0 people online. The `GatewayIntents.GuildPresences` needs to be specified.

**Comment by Scott-Caldwell** [comment]
Ah, yup, good catch. I think we should just remove the online count from that command. It's neat and all, but you can just look at the invite embed in #rules if you want to know how many people are online. Not really worth the perf cost of receiving presence updates, imo.

**Comment by Scott-Caldwell** [comment]
Same thing with the Status field (Online, Offline, Away) in !info. Without presence intent, I think that'll always just show as Offline.

**Comment by Hamsterland** [comment]
Yep, it looks like a candidate to remove. Neat but not used too much. Presences is also the bulkiest intent so not using will be good for memory.
