### ISSUE TITLE
Allow purging messages on user ban

### ISSUE THREAD

**Issue by NullEntity** [discord-csharp/MODiX#819]
As a moderator, I want the option to purge the user's messages when banning them. An example situation is when a new user joins and spams across multiple channels.

The Discord API allows specifying this as a parameter when banning a user: https://discord.com/developers/docs/resources/guild#create-guild-ban

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
