### ISSUE TITLE
Roslyn analysers

### ISSUE THREAD

**Issue by TAGC** [discord-csharp/MODiX#82]
With a bunch of people working on MODiX, we're starting to see some divergence in code conventions. It might be a good idea to chuck some Rosyln analyzers in and make warnings get treated as errors. This will allow us to decide on and enforce one standard code style that we all use for this project.

**Comment by Cisien** [comment]
Great idea, but going to backlog for now since we need to get a functioning bot to replace rowboat by the 1st. I'll take on the job of standardizing the code afterward

**Comment by jmazouri** [comment]
More or less resolved by #203 , though there are still some architectural inconsistencies.
