### ISSUE TITLE
Spam prevention

### ISSUE THREAD

**Issue by patrickklaeren** [discord-csharp/MODiX#84]
MODiX currently has no spam prevention. As discovered in #83, although we purge invite links, there's nothing stopping a user from posting multiple invites and letting MODiX itself spam the channel with replies to the user (as well as the #debug-log).

We need some sort of cooldown or functionality like Rowboat. Rowboat checks the amount of links sent by the user in X timespan, and automutes. Would be good to port that feature,

**Comment by Inzanit** [comment]
#505 may be of interest here.

**Comment by thaumanovic** [comment]
This issue is in large made obsolete by both `MessageContentCheckBehaviour` and Discord's auto mod feature.

**Suggestion action:** Close issue.
