### ISSUE TITLE
Ignore MessageStaff channels in User Lookup

### ISSUE THREAD

**Issue by spixy** [discord-csharp/MODiX#850]
https://mod.gg/userlookup is showing all channels created by @**Message Staff**.
It is not needed, breaks privacy? and makes piechart not to be shown:
![image](https://user-images.githubusercontent.com/4542110/99918664-e470e100-2d18-11eb-8df2-7324aface8be.png)

**Comment by Scott-Caldwell** [comment]
This would be resolved by implementing #699.

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
