### ISSUE TITLE
Paginate service

### ISSUE THREAD

**Issue by Jay-Madden** [discord-csharp/MODiX#851]
Some of the embeds are very large and modix could benefit from a generic service to creates "pages" on the embed that are scrollable via reactions. 

Example:
![Like so](https://user-images.githubusercontent.com/25359755/100027147-3158c400-2dba-11eb-83d9-e4fe5e050544.png)

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
