### ISSUE TITLE
!eval removes indentation when displaying code in the result embed

### ISSUE THREAD

**Issue by Scott-Caldwell** [discord-csharp/MODiX#859]
Issue is present regardless of whether the code in the command was surrounded by a code block when the command was executed.

![image](https://user-images.githubusercontent.com/2829282/109403909-f45b1b00-792e-11eb-9a6d-444d4cc7f3ca.png)

**Comment by ProIcons** [comment]
There are moments that you copy paste code that already intendent by the IDE. which adds multiple levels of indentation and making it look bad on a paste.
Would make sense to indent it after submission on the bot using a linter.

**Comment by Kuinox** [comment]
Found the condition that make it indent properly:  
![image](https://user-images.githubusercontent.com/18743295/109423835-53796800-79e1-11eb-929f-e9991fd95e10.png)
![image](https://user-images.githubusercontent.com/18743295/109423843-62f8b100-79e1-11eb-9b6c-2956ba20998d.png)
If there are multiple levels of indentations, the indentation is conserved.

**Comment by calledude** [comment]
Can this be closed now? See: #984
