### ISSUE TITLE
Provide a way to build embeds with tags

### ISSUE THREAD

**Issue by Scott-Caldwell** [discord-csharp/MODiX#886]

**Comment by n-Ultima** [comment]
Possibly, we could provide a parameter inside the tag command(to call them), to have the name of the tag as a title, and the content of the tag as the description of the embed?

**Comment by n-Ultima** [comment]
Basically, you can call the tag as text or as an embed.

**Comment by JakenVeina** [comment]
I would say tags that are embeds can only be created in the Web Client.
