### ISSUE TITLE
Repl breaks with pattern matching

### ISSUE THREAD

**Issue by Atulin** [discord-csharp/MODiX#904]
https://discord.com/channels/143867839282020352/251386218351165441/867411778841083924

Executing the following code
```cs
class Foo{}
class Bar : Foo{}
class Baz : Foo{}
Foo f = new Bar();
var res = f switch {
  Bar => "bar",
  Baz => "baz",
  _ => "idk"
};
return res;
```
returns
![image](https://user-images.githubusercontent.com/11233299/126507424-baa80414-2227-4469-a3ae-de4d248407b7.png)

and it works just fine on [Sharplab](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMAGAWAChcBGYiogMQHsaACAM3oF56YBTAd3oCEJkACgCUAbkoA3AfWQcAzqyb05XKAgDGAC3oBvYvT7SWAPnoAiYALNx9hgF6tTFiHeu2A+o/NQAJgGs3IgBfcSJiLFIATkFZOTFKXHpaGh0g8JxDZHoQJLpU9Pts3JSgoA==)

**Comment by Scott-Caldwell** [comment]
This is a known Roslyn issue in interactive/CSharpScript: https://github.com/dotnet/roslyn/issues/49529
