### ISSUE TITLE
Clicking on infraction detail not showing infraction

### ISSUE THREAD

**Issue by spixy** [discord-csharp/MODiX#936]
Clicking on infraction detail requested by `!infractions` command opens https://mod.gg/infractions?id={{id}} which then redirects to https://mod.gg/logs/infractions?id={{id}}.
Filter bellow ID column is correctly filled with `{{id}}` but results are not filtered by this filter and show some other infractions.

Same with https://mod.gg/logs/infractions?subject={{subject}}.

**Comment by Scott-Caldwell** [comment]
I'm unable to reproduce. Are you logged in to mod.gg?

**Comment by spixy** [comment]
Of course.
> Filter bellow ID column is correctly filled with {{id}} but results are not filtered by this filter and show some other infractions.

See on screenshot:

![image](https://user-images.githubusercontent.com/4542110/139699273-f7f631c1-b80f-4bed-99aa-bb460bbc9b35.png)

**Comment by Scott-Caldwell** [comment]
I see.. it seems like the issue only repros if you have the Show State checkbox unchecked. (At least for me.)
