### ISSUE TITLE
!eval should truncate the type name if it's too long to fit in an embed field

### ISSUE THREAD

**Issue by Scott-Caldwell** [discord-csharp/MODiX#939]
For example, the following currently fails with "Error: Field name length must be less than or equal to 256. (Parameter 'Name')":
`!eval (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)`

**Comment by tebeco** [comment]
I see you found my stupid example :D
