### ISSUE TITLE
Rollout Data Seeding

### ISSUE THREAD

**Issue by Inzanit** [discord-csharp/MODiX#96]
As we're not keeping a history of migrations and everyone is recreating initial migrations, some people may rely on data to be inserted/modified as part of their migration; these would be deleted when merged and someone else rescaffolds the initial migration. This issue serves as a homebase for all "manually" added migration members.

Comments on this issue with a common layout may be a good way of conveying this. Format I suggest, short and simple:

## Issue ref and small summary ##

```Code that needs to be inserted```

**Comment by Inzanit** [comment]
## #32 Configurations for invites to be added ##
Place unique constraint, when creating table:
```table.UniqueConstraint("IX_Category_Key", arg => new { arg.Category, arg.Key });```

Insert data:
```
migrationBuilder.InsertData("BehaviourConfigurations", new[] { "Category", "Key", "Value" }, new[] { BehaviourCategory.InvitePurging.ToString(), "IsEnabled", "True" });
migrationBuilder.InsertData("BehaviourConfigurations", new[] { "Category", "Key", "Value" }, new[] { BehaviourCategory.InvitePurging.ToString(), "ExemptRoleIds", "[268470383571632128,155770800392110082,155771334779994112,410138389283602432]" });
migrationBuilder.InsertData("BehaviourConfigurations", new[] { "Category", "Key", "Value" }, new[] { BehaviourCategory.InvitePurging.ToString(), "LoggingChannelId", "380603776412811267" });```

**Comment by JakenVeina** [comment]
This should be a moot point now, since we've started not re-building `Initial` on each PR (at least, I have).
