### ISSUE TITLE
Remove Pingroles

### ISSUE THREAD

**Issue by Scott-Caldwell** [discord-csharp/MODiX#973]
Discord's new [Community Onboarding feature](https://support.discord.com/hc/en-us/articles/11074987197975-Community-Onboarding-FAQ) allows servers to configure roles and channels that users can self-assign.

**Comment by tacosontitan** [comment]
I noticed the `pingroles` module is [still being modified](https://github.com/discord-csharp/MODiX/commits/main/Modix.Bot/Modules/PingRoleModule.cs):

![image](https://github.com/discord-csharp/MODiX/assets/65432314/511c4790-bcd7-4a61-9007-886882dd1cca)

Is the direction still to remove this module?

**Comment by tacosontitan** [comment]
Following up on this.

**Comment by patrickklaeren** [comment]
@tacosontitan Yep, ready to be worked on.
