### ISSUE TITLE
Quote service does not properly handle braces if there is prelink content

### ISSUE THREAD

**Issue by MangoDevx** [discord-csharp/MODiX#978]
In Services/Quote/MessagingLinkBehavior.cs line 67 is a problem with brace checking if prelink content exists. Linked is a PR to this issue which contains a fix by checking the prelink content suffix. A Regex solution may be more suitable with the design.
PR ref: #979.

Example:
Hey! \<message link\>

Expected Behavior:
Modix ignores and does not embed

Actual Behavior:
Modix posts an embded to the message at the message link

**Comment by Scott-Caldwell** [comment]
Fixed in #979
