### ISSUE TITLE
Infrastructure migration

### ISSUE THREAD

**Issue by patrickklaeren** [discord-csharp/MODiX#997]
@Cisien is retiring. The following tracks what is necessary to migrate:

- [x] GitHub organisation ownership
- [x] Issue clean up, get rid of stale issues
- [x] Azure Pipelines (should involve moving pipeline definitions to in-repo)
- [x] Contact .NET Foundation

Pending internal discussion on C# Guild between staff.

People are encouraged to create new issues should they disagree with stale issues being closed.

https://github.com/discord-csharp/MODiX/blob/cf8ec3dbdf948e78f3bd44ac05dbecfb43f9b90b/docker-stack.yml#L15

**Comment by Cisien** [comment]
the docker stack and kube config in the repo is (mostly) for other's to self-host the bot, it's not representative of the running config.

as for that string highlighted, it's just for the LetsEncrypt cert, feel free to update it to something else. 

I have updated the org ownership to include @patrickklaeren 

Portainer is used to view and manage the infra, you can access it at https://portainer.mod.gg -- let me know if you have perms there to do things. I might have to do things.
